// <auto-generated />
using System;
using Cashflowpoly.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cashflowpoly.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cashflowpoly.Api.Data.AppUserEf", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("app_users_username_key");

                    b.HasIndex("Role", "IsActive")
                        .HasDatabaseName("ix_app_users_role_active");

                    b.ToTable("app_users", null, t =>
                        {
                            t.HasCheckConstraint("app_users_role_check", "role in ('INSTRUCTOR','PLAYER')");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.CashflowProjectionDb", b =>
                {
                    b.Property<Guid>("ProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("projection_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("counterparty");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("direction");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("EventPk")
                        .HasColumnType("uuid")
                        .HasColumnName("event_pk");

                    b.Property<string>("Note")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("note");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("ProjectionId");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_ecp_category");

                    b.HasIndex("EventPk");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("event_cashflow_projections_session_id_event_id_key");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("ix_ecp_session_time");

                    b.HasIndex("SessionId", "PlayerId", "Timestamp")
                        .HasDatabaseName("ix_ecp_session_player_time");

                    b.ToTable("event_cashflow_projections", null, t =>
                        {
                            t.HasCheckConstraint("event_cashflow_projections_amount_check", "amount > 0");

                            t.HasCheckConstraint("event_cashflow_projections_direction_check", "direction in ('IN','OUT')");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.EventDb", b =>
                {
                    b.Property<Guid>("EventPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_pk");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("actor_type");

                    b.Property<string>("ClientRequestId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("client_request_id");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("day_index");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("weekday");

                    b.HasKey("EventPk");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_events_payload_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("RulesetVersionId");

                    b.HasIndex("PlayerId", "Timestamp")
                        .HasDatabaseName("ix_events_player_time");

                    b.HasIndex("SessionId", "ActionType")
                        .HasDatabaseName("ix_events_session_action");

                    b.HasIndex("SessionId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("events_session_id_event_id_key");

                    b.HasIndex("SessionId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_events_session_seq");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("ix_events_session_time");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("events_actor_type_check", "actor_type in ('PLAYER','SYSTEM')");

                            t.HasCheckConstraint("events_day_index_check", "day_index >= 0");

                            t.HasCheckConstraint("events_sequence_number_check", "sequence_number >= 0");

                            t.HasCheckConstraint("events_turn_number_check", "turn_number >= 1");

                            t.HasCheckConstraint("events_weekday_check", "weekday in ('MON','TUE','WED','THU','FRI','SAT','SUN')");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.MetricSnapshotDb", b =>
                {
                    b.Property<Guid>("MetricSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("metric_snapshot_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("metric_name");

                    b.Property<string>("MetricValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metric_value_json");

                    b.Property<double?>("MetricValueNumeric")
                        .HasColumnType("double precision")
                        .HasColumnName("metric_value_numeric");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("MetricSnapshotId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetVersionId")
                        .HasDatabaseName("ix_metrics_ruleset_version");

                    b.HasIndex("SessionId", "MetricName", "ComputedAt")
                        .HasDatabaseName("ix_metrics_session_name_time");

                    b.HasIndex("SessionId", "PlayerId", "ComputedAt")
                        .HasDatabaseName("ix_metrics_session_player_time");

                    b.HasIndex("SessionId", "PlayerId", "MetricName", "ComputedAt")
                        .HasDatabaseName("ix_metrics_session_player_name_time");

                    b.ToTable("metric_snapshots", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.PlayerDb", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("InstructorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_user_id");

                    b.HasKey("PlayerId");

                    b.HasIndex("InstructorUserId", "CreatedAt")
                        .HasDatabaseName("ix_players_instructor_user");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.RulesetDb", b =>
                {
                    b.Property<Guid>("RulesetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("InstructorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("RulesetId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rulesets_created_at");

                    b.HasIndex("InstructorUserId", "CreatedAt")
                        .HasDatabaseName("ix_rulesets_instructor_user");

                    b.ToTable("rulesets", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.RulesetVersionDb", b =>
                {
                    b.Property<Guid>("RulesetVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("config_hash");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("RulesetVersionId");

                    b.HasIndex("ConfigJson")
                        .HasDatabaseName("ix_ruleset_versions_config_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ConfigJson"), "gin");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ruleset_versions_status");

                    b.HasIndex("RulesetId", "ConfigHash")
                        .IsUnique()
                        .HasDatabaseName("ruleset_versions_ruleset_id_config_hash_key");

                    b.HasIndex("RulesetId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_ruleset_versions_ruleset");

                    b.ToTable("ruleset_versions", null, t =>
                        {
                            t.HasCheckConstraint("ruleset_versions_status_check", "status in ('DRAFT','ACTIVE','RETIRED')");

                            t.HasCheckConstraint("ruleset_versions_version_check", "version >= 1");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SecurityAuditLogDb", b =>
                {
                    b.Property<Guid>("SecurityAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("security_audit_log_id");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("path");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("username");

                    b.HasKey("SecurityAuditLogId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_security_audit_logs_occurred");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("ix_security_audit_logs_event");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_security_audit_logs_user");

                    b.ToTable("security_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("security_audit_logs_outcome_check", "outcome in ('SUCCESS','FAILURE','DENIED')");

                            t.HasCheckConstraint("security_audit_logs_status_code_check", "status_code >= 100 and status_code <= 599");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionDb", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("InstructorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_user_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mode");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("session_name");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sessions_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessions_status");

                    b.HasIndex("InstructorUserId", "CreatedAt")
                        .HasDatabaseName("ix_sessions_instructor_user");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("sessions_mode_check", "mode in ('PEMULA','MAHIR')");

                            t.HasCheckConstraint("sessions_status_check", "status in ('CREATED','STARTED','ENDED')");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionPlayerEf", b =>
                {
                    b.Property<Guid>("SessionPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("JoinOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("join_order");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PLAYER")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("SessionPlayerId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_session_players_player");

                    b.HasIndex("SessionId", "JoinOrder")
                        .HasDatabaseName("ix_session_players_session");

                    b.HasIndex("SessionId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("session_players_session_id_player_id_key");

                    b.ToTable("session_players", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_players_role", "role in ('PLAYER')");

                            t.HasCheckConstraint("session_players_join_order_check", "join_order >= 1");
                        });
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionRulesetActivationEf", b =>
                {
                    b.Property<Guid>("ActivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activation_id");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ActivatedBy")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("activated_by");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("ActivationId");

                    b.HasIndex("RulesetVersionId")
                        .HasDatabaseName("ix_sra_ruleset_version");

                    b.HasIndex("SessionId", "ActivatedAt")
                        .HasDatabaseName("ix_sra_session");

                    b.ToTable("session_ruleset_activations", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.UserPlayerLinkEf", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_player_links_player");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_player_links_user");

                    b.ToTable("user_player_links", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.ValidationLogEf", b =>
                {
                    b.Property<Guid>("ValidationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("validation_log_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("EventPk")
                        .HasColumnType("uuid")
                        .HasColumnName("event_pk");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("ValidationLogId");

                    b.HasIndex("EventPk");

                    b.HasIndex("IsValid")
                        .HasDatabaseName("ix_validation_valid");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_validation_session_time");

                    b.HasIndex("SessionId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("validation_logs_session_id_event_id_key");

                    b.ToTable("validation_logs", (string)null);
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.CashflowProjectionDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.EventDb", null)
                        .WithMany()
                        .HasForeignKey("EventPk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("event_cashflow_projections_event_pk_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.PlayerDb", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("event_cashflow_projections_player_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("event_cashflow_projections_session_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.EventDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.PlayerDb", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("events_player_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.RulesetVersionDb", null)
                        .WithMany()
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("events_ruleset_version_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("events_session_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.MetricSnapshotDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.PlayerDb", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("metric_snapshots_player_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.RulesetVersionDb", null)
                        .WithMany()
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("metric_snapshots_ruleset_version_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("metric_snapshots_session_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.PlayerDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.AppUserEf", null)
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("players_instructor_user_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.RulesetDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.AppUserEf", null)
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("rulesets_instructor_user_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.RulesetVersionDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.RulesetDb", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ruleset_versions_ruleset_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SecurityAuditLogDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.AppUserEf", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("security_audit_logs_user_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionDb", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.AppUserEf", null)
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("sessions_instructor_user_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionPlayerEf", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.PlayerDb", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("session_players_player_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_players_session_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.SessionRulesetActivationEf", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.RulesetVersionDb", null)
                        .WithMany()
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("session_ruleset_activations_ruleset_version_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_ruleset_activations_session_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.UserPlayerLinkEf", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.PlayerDb", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_player_links_player_id_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.AppUserEf", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_player_links_user_id_fkey");
                });

            modelBuilder.Entity("Cashflowpoly.Api.Data.ValidationLogEf", b =>
                {
                    b.HasOne("Cashflowpoly.Api.Data.EventDb", null)
                        .WithMany()
                        .HasForeignKey("EventPk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("validation_logs_event_pk_fkey");

                    b.HasOne("Cashflowpoly.Api.Data.SessionDb", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("validation_logs_session_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
