// Fungsi file: Menyediakan utilitas infrastruktur UI untuk kebutuhan UiText.
using Cashflowpoly.Ui.Models;

namespace Cashflowpoly.Ui.Infrastructure;

/// <summary>
/// Menyatakan peran utama tipe UiText pada modul ini.
/// </summary>
public static class UiText
{
    /// <summary>
    /// Menjalankan fungsi new sebagai bagian dari alur file ini.
    /// </summary>
    private static readonly Dictionary<string, (string Id, string En)> Lexicon = new(StringComparer.OrdinalIgnoreCase)
    {
        ["brand.chip"] = ("Lembar Petualang", "Adventurer's Ledger"),

        ["nav.home"] = ("Beranda", "Home"),
        ["nav.sessions"] = ("Sesi Permainan", "Game Sessions"),
        ["nav.players"] = ("Direktori Pemain", "Player Directory"),
        ["nav.analytics"] = ("Analitika", "Analytics"),
        ["nav.ruleset"] = ("Set Aturan", "Rulesets"),
        ["nav.privacy"] = ("Buku Aturan", "Rulebook"),

        ["auth.login"] = ("Masuk", "Sign In"),
        ["auth.logout"] = ("Keluar", "Logout"),
        ["auth.access"] = ("Akses Dasbor", "Dashboard Access"),
        ["auth.title"] = ("Masuk ke Cashflowpoly", "Sign In to Cashflowpoly"),
        ["auth.subtitle"] = ("Masuk dengan akun instruktur atau pemain untuk melanjutkan.", "Sign in with an instructor or player account to continue."),
        ["auth.display_name"] = ("Nama Tampilan", "Display Name"),
        ["auth.username"] = ("Nama Pengguna", "Username"),
        ["auth.password"] = ("Kata Sandi", "Password"),
        ["auth.submit"] = ("Masuk", "Sign In"),
        ["auth.no_account"] = ("Belum punya akun?", "Don't have an account?"),
        ["auth.have_account"] = ("Sudah punya akun?", "Already have an account?"),
        ["auth.register"] = ("Daftar", "Register"),
        ["auth.register_title"] = ("Buat Akun Baru", "Register New Account"),
        ["auth.register_subtitle"] = ("Buat akun baru agar bisa login ke game melalui API.", "Create a new account to sign in to the game through the API."),
        ["auth.confirm_password"] = ("Konfirmasi Kata Sandi", "Confirm Password"),
        ["auth.role"] = ("Peran Pengguna", "User Role"),
        ["auth.role_player"] = ("Pemain", "Player"),
        ["auth.role_instructor"] = ("Instruktur", "Instructor"),
        ["auth.submit_register"] = ("Buat Akun", "Create Account"),
        ["auth.login_panel_title"] = ("Sudah Punya Akun?", "Already Have an Account?"),
        ["auth.login_panel_desc"] = ("Masuk dengan akun Anda untuk melanjutkan pekerjaan.", "Sign in with your account to continue your work."),
        ["auth.login_panel_cta"] = ("MASUK", "SIGN IN"),
        ["auth.register_panel_title"] = ("Belum Punya Akun?", "Don't Have an Account Yet?"),
        ["auth.register_panel_desc"] = ("Buat akun baru untuk mulai mengelola sesi dan analitika.", "Create a new account to start managing sessions and analytics."),
        ["auth.register_panel_cta"] = ("DAFTAR", "REGISTER"),
        ["auth.placeholder.full_name"] = ("Nama Lengkap", "Full Name"),
        ["auth.placeholder.new_username"] = ("pemain_baru", "new_player"),
        ["auth.login_note.quick_access"] = ("Akses sesi lebih cepat", "Faster session access"),
        ["auth.login_note.realtime_monitoring"] = ("Pemantauan analitika waktu nyata", "Real-time analytics monitoring"),
        ["auth.login_note.centralized_ruleset"] = ("Manajemen Set Aturan terpusat", "Centralized ruleset management"),
        ["auth.error.login_required"] = ("Nama Pengguna dan Kata Sandi wajib diisi.", "Username and password are required."),
        ["auth.error.login_failed"] = ("Login gagal.", "Login failed."),
        ["auth.error.login_response_invalid"] = ("Respons login tidak valid.", "Invalid login response."),
        ["auth.error.register_required"] = ("Nama tampilan, Nama Pengguna, Kata Sandi, dan konfirmasi Kata Sandi wajib diisi.", "Display name, username, password, and confirmation are required."),
        ["auth.error.role_invalid"] = ("Peran tidak valid.", "Invalid role."),
        ["auth.error.confirm_mismatch"] = ("Konfirmasi Kata Sandi tidak sama.", "Password confirmation does not match."),
        ["auth.error.register_failed"] = ("Registrasi gagal.", "Registration failed."),
        ["auth.error.register_response_invalid"] = ("Respons registrasi tidak valid.", "Invalid registration response."),

        ["lang.label"] = ("Bahasa", "Language"),
        ["lang.code.id"] = ("ID", "ID"),
        ["lang.code.en"] = ("EN", "EN"),
        ["lang.option.id"] = ("Bahasa Indonesia (ID)", "Indonesian (ID)"),
        ["lang.option.en"] = ("Bahasa Inggris (EN)", "English (EN)"),

        ["profile.settings"] = ("Pengaturan Web", "Web Settings"),
        ["profile.role"] = ("Peran", "Role"),
        ["layout.skip_to_content"] = ("Lewati ke konten", "Skip to content"),
        ["layout.toggle_nav"] = ("Buka/tutup menu navigasi", "Toggle navigation menu"),
        ["layout.logo_alt"] = ("Logo Cashflowpoly", "Cashflowpoly logo"),
        ["layout.profile_alt"] = ("Profil", "Profile"),
        ["layout.brand_name"] = ("Cashflowpoly", "Cashflowpoly"),
        ["layout.quickstart.aria"] = ("Panduan cepat penggunaan", "Quick usage guide"),
        ["layout.quickstart.kicker"] = ("Mulai dari sini", "Start here"),
        ["layout.quickstart.hide"] = ("Sembunyikan panduan", "Hide guide"),
        ["layout.quickstart.show"] = ("Tampilkan panduan", "Show guide"),
        ["layout.quickstart.current"] = ("Anda sedang di langkah ini", "You are currently on this step"),
        ["layout.quickstart.open_menu"] = ("Buka menu", "Open menu"),
        ["layout.quickstart.instructor.title"] = ("Alur cepat instruktur", "Instructor quick flow"),
        ["layout.quickstart.instructor.subtitle"] = ("Ikuti 4 langkah ini agar setup, eksekusi sesi, dan evaluasi berjalan rapi.", "Follow these 4 steps to keep setup, session execution, and evaluation organized."),
        ["layout.quickstart.instructor.step1.title"] = ("Siapkan Set Aturan", "Prepare Rulesets"),
        ["layout.quickstart.instructor.step1.desc"] = ("Buat atau pilih versi aturan yang paling sesuai untuk sesi belajar.", "Create or pick the most suitable ruleset version for the learning session."),
        ["layout.quickstart.instructor.step2.title"] = ("Buka dan cek sesi", "Open and review sessions"),
        ["layout.quickstart.instructor.step2.desc"] = ("Masuk ke Sesi Permainan, pilih sesi aktif, lalu cek analitik ringkas.", "Go to Game Sessions, choose an active session, then review summary analytics."),
        ["layout.quickstart.instructor.step3.title"] = ("Evaluasi per pemain", "Evaluate each player"),
        ["layout.quickstart.instructor.step3.desc"] = ("Buka Direktori Pemain untuk melihat detail performa dan progres individu.", "Open Player Directory to inspect detailed performance and individual progress."),
        ["layout.quickstart.instructor.step4.title"] = ("Finalisasi aturan", "Finalize rules"),
        ["layout.quickstart.instructor.step4.desc"] = ("Gunakan Buku Aturan sebagai acuan sebelum menjalankan sesi berikutnya.", "Use the Rulebook as reference before running the next session."),
        ["layout.quickstart.player.title"] = ("Alur cepat pemain", "Player quick flow"),
        ["layout.quickstart.player.subtitle"] = ("Pahami langkah inti berikut agar mudah membaca progres permainan Anda.", "Understand these core steps to read your gameplay progress easily."),
        ["layout.quickstart.player.step1.title"] = ("Pilih sesi", "Pick a session"),
        ["layout.quickstart.player.step1.desc"] = ("Masuk ke Sesi Permainan dan pilih sesi yang sedang berlangsung.", "Go to Game Sessions and choose the ongoing session."),
        ["layout.quickstart.player.step2.title"] = ("Baca progres sesi", "Read session progress"),
        ["layout.quickstart.player.step2.desc"] = ("Buka rincian sesi untuk melihat ringkasan poin, cashflow, dan status aturan.", "Open session details to view score summary, cashflow, and rule status."),
        ["layout.quickstart.player.step3.title"] = ("Pahami Set Aturan", "Understand rulesets"),
        ["layout.quickstart.player.step3.desc"] = ("Lihat rincian Set Aturan aktif agar tahu batasan dan target permainan.", "Review active ruleset details to understand constraints and gameplay targets."),
        ["layout.quickstart.player.step4.title"] = ("Rujuk Buku Aturan", "Consult the Rulebook"),
        ["layout.quickstart.player.step4.desc"] = ("Gunakan Buku Aturan untuk memastikan istilah dan mekanik yang digunakan.", "Use the Rulebook to confirm the terms and mechanics being used."),
        ["footer.rulebook_copyright"] = ("Hak Cipta Buku Aturan", "Rulebook Copyright"),

        ["home.badge"] = ("Cashflowpoly", "Cashflowpoly"),
        ["home.title"] = ("Dashboard Analitika dan Set Aturan.", "Analytics and Ruleset Dashboard."),
        ["home.subtitle"] = ("Pantau sesi, performa pemain, dan aturan aktif dalam satu tempat.", "Monitor sessions, player performance, and active rules in one place."),
        ["home.player_badge"] = ("Dasbor Pemain", "Player Dashboard"),
        ["home.player_title"] = ("Pantau progres permainan Anda secara Waktu Nyata.", "Track your game progress in real time."),
        ["home.player_subtitle"] = ("Lihat status sesi, Set Aturan yang dapat Anda akses, dan ringkasan performa pribadi tanpa perlu membuka menu instruktur.", "View session status, accessible rulesets, and your personal performance summary without opening the instructor menu."),
        ["home.cta.sessions"] = ("Buka Sesi", "Open Sessions"),
        ["home.cta.analytics"] = ("Buka Analitika", "Open Analytics"),
        ["home.cta.my_progress"] = ("Lihat progres saya", "View my progress"),
        ["home.cta.open_ruleset"] = ("Buka Set Aturan", "Open rulesets"),
        ["home.feature.1"] = ("Validasi Buku Aturan dan skor otomatis.", "Automatic rulebook validation and scoring."),
        ["home.feature.2"] = ("Aktivasi Set Aturan per sesi dengan cepat.", "Quick per-session ruleset activation."),
        ["home.feature.3"] = ("Cuplikan arus kas dan pelanggaran.", "Cashflow and violation snapshots."),
        ["home.feature.4"] = ("Ringkasan pemain siap untuk evaluasi.", "Player summaries ready for evaluation."),
        ["home.player.feature.1"] = ("Pilih sesi dari menu Sesi Permainan untuk membuka rincian progres tanpa mengetik ID sesi manual.", "Pick a session from Game Sessions to open progress details without typing a session ID manually."),
        ["home.player.feature.2"] = ("Lihat metrik Arus Kas dan poin Anda dalam satu Dasbor.", "See your cashflow and points in one dashboard."),
        ["home.player.feature.3"] = ("Cek Set Aturan aktif untuk memahami target skor dan penalti.", "Check active rulesets to understand score targets and penalties."),
        ["home.player.feature.4"] = ("Pantau pembaruan data otomatis setiap 30 detik.", "Monitor automatic data updates every 30 seconds."),
        ["home.total_sessions"] = ("Total Sesi", "Total Sessions"),
        ["home.my_sessions"] = ("Sesi saya", "My sessions"),
        ["home.peers_in_session"] = ("Teman satu sesi", "Session peers"),
        ["home.available_rulesets"] = ("Set Aturan tersedia", "Available rulesets"),
        ["home.active_sessions"] = ("Sesi Aktif", "Active Sessions"),
        ["home.realtime"] = ("Waktu Nyata", "Real-time"),
        ["home.live"] = ("LANGSUNG", "LIVE"),
        ["home.server_time"] = ("Waktu server lokal", "Local server time"),
        ["home.sync_label"] = ("Sinkron data", "Data sync"),
        ["home.auto_refresh_note"] = ("Data diperbarui otomatis setiap 30 detik.", "Data refreshes automatically every 30 seconds."),
        ["home.error.realtime_status"] = ("Gagal sinkron waktu nyata ({status}).", "Realtime sync failed ({status})."),
        ["home.error.realtime_network"] = ("Gagal sinkron waktu nyata (kesalahan jaringan).", "Realtime sync failed (network error)."),
        ["home.error.partial_realtime_failed"] = ("Sebagian data waktu nyata gagal dimuat ({details}).", "Some realtime data failed to load ({details})."),
        ["home.ruleset_active"] = ("Set Aturan Aktif", "Active Ruleset"),
        ["home.players_monitored"] = ("Pemain Dipantau", "Players Monitored"),
        ["home.snapshot_demo"] = ("Cuplikan singkat untuk demo tampilan.", "Quick snapshot for UI demo."),
        ["home.guide.menu"] = ("Panduan Menu", "Menu Guide"),
        ["home.guide.title"] = ("Kumpulan cara penggunaan", "Usage playbook"),
        ["home.guide.subtitle"] = ("Gunakan panduan cepat ini supaya alur kerja dari Persiapan sampai Rincian Sesi dan Analitika Sesi lebih rapi.", "Use this quick guide to keep the workflow from setup to Session Details and Session Analytics organized."),
        ["home.guide.sessions.title"] = ("Sesi", "Sessions"),
        ["home.guide.sessions.desc"] = ("Buka daftar sesi, pilih sesi aktif, lalu masuk Rincian Pemain untuk analitik per individu.", "Open the session list, pick an active session, then open Player Details for per-player analytics."),
        ["home.guide.sessions.link"] = ("Buka menu Sesi", "Open Sessions"),
        ["home.guide.ruleset.title"] = ("Set Aturan", "Rulesets"),
        ["home.guide.ruleset.desc"] = ("Buat Set Aturan baru, cek versi, aktifkan versi yang tepat sebelum sesi dimulai.", "Create a new ruleset, review versions, and activate the right one before a session starts."),
        ["home.guide.ruleset.link"] = ("Buka menu Set Aturan", "Open Rulesets"),
        ["home.guide.analytics.title"] = ("Analitika", "Analytics"),
        ["home.guide.analytics.desc"] = ("Buka Rincian Sesi dari daftar sesi untuk melihat ringkasan arus kas, metrik misi, dan performa pemain.", "Open Session Details from the session list to view cashflow summaries, mission metrics, and player performance."),
        ["home.guide.analytics.link"] = ("Buka Rincian Sesi", "Open Session Details"),
        ["home.guide.players.title"] = ("Pemain", "Players"),
        ["home.guide.players.desc"] = ("Lihat direktori pemain untuk validasi identitas sebelum meninjau Rincian metrik.", "Review the player directory to validate identities before inspecting metric details."),
        ["home.guide.players.link"] = ("Buka menu Pemain", "Open Players"),
        ["home.quick_flow.title"] = ("Alur Penggunaan Cepat", "Quick Workflow"),
        ["home.quick_flow.step1"] = ("Persiapan Set Aturan yang dibutuhkan di menu Set Aturan.", "Set up required rulesets in the Rulesets menu."),
        ["home.quick_flow.step2"] = ("Masuk menu Sesi, pilih sesi, lalu aktifkan Set Aturan.", "Go to Sessions, choose a session, then activate a ruleset."),
        ["home.quick_flow.step3"] = ("Kirim aktivitas permainan dari aplikasi permainan ke sistem.", "Send gameplay events from the game app into the system."),
        ["home.quick_flow.step4"] = ("Buka Rincian dan Analitika Sesi untuk ringkasan sesi dan tren metrik.", "Open Session Details and Analytics for session summaries and metric trends."),
        ["home.quick_flow.step5"] = ("Buka Rincian Pemain untuk evaluasi performa per individu.", "Open Player Details for per-player performance evaluation."),
        ["home.player_guide.menu"] = ("Panduan Pemain", "Player Guide"),
        ["home.player_guide.title"] = ("Langkah cepat melihat progres", "Quick steps to view progress"),
        ["home.player_guide.subtitle"] = ("Tampilan pemain difokuskan untuk membaca hasil permainan Anda dengan cepat.", "The player view is focused on reading your own game results quickly."),
        ["home.player_guide.analytics.title"] = ("Analitika Sesi Saya", "My Session Analytics"),
        ["home.player_guide.analytics.desc"] = ("Pilih sesi dari menu Sesi, lalu buka Rincian Sesi untuk melihat arus kas, poin, dan risiko pribadi.", "Select a session from the Sessions menu, then open Session Details to view your cashflow, points, and personal risk."),
        ["home.player_guide.analytics.link"] = ("Buka menu Sesi", "Open Sessions"),
        ["home.player_guide.ruleset.title"] = ("Set Aturan Aktif", "Active Rulesets"),
        ["home.player_guide.ruleset.desc"] = ("Lihat daftar Set Aturan untuk memahami target poin, penalti, dan batasan aksi permainan.", "View the ruleset list to understand point targets, penalties, and gameplay action limits."),
        ["home.player_guide.ruleset.link"] = ("Buka Set Aturan", "Open Rulesets"),
        ["home.player_guide.rulebook.title"] = ("Buku Aturan", "Rulebook"),
        ["home.player_guide.rulebook.desc"] = ("Buka Buku Aturan kapan saja saat butuh klarifikasi aturan permainan.", "Open the rulebook anytime when you need rule clarifications."),
        ["home.player_guide.rulebook.link"] = ("Buka Buku Aturan", "Open Rulebook"),
        ["home.player_flow.title"] = ("Alur Pemain yang Disarankan", "Recommended Player Flow"),
        ["home.player_flow.step1"] = ("Masuk ke Sesi Permainan lalu pilih sesi yang sedang Anda ikuti.", "Open Game Sessions then choose the session you are in."),
        ["home.player_flow.step2"] = ("Pantau Bersih Arus Kas dan poin kebutuhan untuk evaluasi keputusan harian.", "Monitor net cashflow and need points to evaluate daily decisions."),
        ["home.player_flow.step3"] = ("Periksa penalti misi dan status pinjaman untuk menghindari skor turun.", "Check mission penalties and loan status to avoid score drops."),
        ["home.player_flow.step4"] = ("Cocokkan progres Anda dengan Set Aturan agar strategi berikutnya lebih tepat.", "Match your progress with the ruleset so your next strategy is more accurate."),

        ["privacy.title"] = ("Buku Aturan Cashflowpoly", "Cashflowpoly Rulebook"),
        ["privacy.outline_title"] = ("Daftar Isi Aturan", "Rulebook Contents"),
        ["privacy.total_sections"] = ("Jumlah Bagian Aturan", "Total Rulebook Sections"),
        ["privacy.total_points"] = ("Jumlah Aturan Skoring", "Total Scoring Rules"),
        ["privacy.back_to_top"] = ("Kembali ke atas", "Back to top"),
        ["privacy.empty_sections"] = ("Bagian Buku Aturan belum tersedia.", "Rulebook sections are not available yet."),
        ["privacy.empty_scoring"] = ("Ringkasan poin belum tersedia.", "Scoring summary is not available yet."),
        ["privacy.happiness_summary"] = ("Ringkasan Poin Kebahagiaan", "Happiness Points Summary"),
        ["privacy.copyright_title"] = ("Hak Cipta Buku Aturan", "Rulebook Copyright"),
        ["privacy.copyright_desc"] = ("Materi Buku Aturan Cashflowpoly digunakan untuk keperluan pembelajaran internal. Dilarang menyalin, menggandakan, atau mendistribusikan ulang tanpa izin tertulis dari pemilik hak cipta.", "Cashflowpoly rulebook materials are for internal learning purposes. Copying, reproducing, or redistributing without written permission from the copyright owner is prohibited."),
        ["privacy.category"] = ("Kategori", "Category"),
        ["privacy.rule"] = ("Aturan", "Rule"),

        ["analytics.dashboard"] = ("Pusat Analitika", "Analytics Center"),
        ["analytics.title"] = ("Analitika Sesi", "Session Analytics"),
        ["analytics.subtitle"] = ("Pilih sesi untuk melihat pembagian metrik Part 1 (variabel fisik) dan Part 2 (metrik turunan).", "Select a session to view Part 1 (physical variables) and Part 2 (derived metrics) breakdowns."),
        ["analytics.button"] = ("Tampilkan Analitika Sesi", "Show Session Analytics"),
        ["analytics.player_dashboard"] = ("Dasbor Progres Pemain", "Player Progress Dashboard"),
        ["analytics.player_title"] = ("Analitika Sesi Saya", "My Session Analytics"),
        ["analytics.player_subtitle"] = ("Pilih sesi yang Anda ikuti untuk melihat ringkasan performa dan metrik pribadi Anda.", "Select a session you joined to view your performance summary and personal metrics."),
        ["analytics.player_no_sessions"] = ("Belum ada sesi untuk akun pemain ini", "No sessions available for this player account"),
        ["analytics.player_button"] = ("Tampilkan Progres Saya", "Show My Progress"),
        ["analytics.workbench_title"] = ("Analitika Sesi", "Session Analytics"),
        ["analytics.workbench_subtitle"] = ("Pilih satu sesi, lalu semua ringkasan tampil otomatis.", "Pick one session, then all summaries appear automatically."),
        ["analytics.section.session_title"] = ("Pilih Sesi Analisis", "Select Session for Analysis"),
        ["analytics.section.session_desc"] = ("Pilih sesi lalu sistem menampilkan matriks Part 1 dan Part 2 per pemain.", "Select a session and the system will show Part 1 and Part 2 matrices per player."),
        ["analytics.section.minimum_matrix_title"] = ("Matriks Metrik Minimum", "Minimum Metrics Matrix"),
        ["analytics.section.minimum_matrix_desc"] = ("Tabel audit metrik minimum per pemain sesuai definisi cuplikan analitika.", "Audit table of minimum per-player metrics based on analytics snapshot definitions."),
        ["analytics.section.part1_title"] = ("Part 1: Variabel Permainan Fisik", "Part 1: Physical Gameplay Variables"),
        ["analytics.section.part1_desc"] = ("Ringkasan lintas pemain untuk variabel mentah observasi permainan.", "Cross-player snapshot for raw, observable gameplay variables."),
        ["analytics.section.part2_title"] = ("Part 2: Metrik Turunan & Outcome", "Part 2: Derived Metrics & Outcomes"),
        ["analytics.section.part2_desc"] = ("Ringkasan lintas pemain untuk metrik turunan, poin, dan status risiko-misi.", "Cross-player snapshot for derived metrics, points, and mission-risk status."),
        ["analytics.section.ruleset_title"] = ("Ringkasan Set Aturan Aktif Sesi", "Session Active Ruleset Summary"),
        ["analytics.tips.instructor"] = ("Tips membaca analitika sesi", "Session analytics tips"),
        ["analytics.tips.player"] = ("Tips membaca progres analitika Anda", "Your analytics progress tips"),
        ["analytics.tip_key.input"] = ("Masukan", "Input"),
        ["analytics.tip_key.interpretation"] = ("Interpretasi", "Interpretation"),
        ["analytics.tip_key.followup"] = ("Tindak lanjut", "Follow-up"),
        ["analytics.tip_key.select_session"] = ("Pilih Sesi", "Select Session"),
        ["analytics.tip_key.focus_score"] = ("Fokus Skor", "Score Focus"),
        ["analytics.tip_key.risk_control"] = ("Kontrol Risiko", "Risk Control"),
        ["analytics.tip.input"] = ("Pilih sesi dari daftar Sesi, lalu buka Rincian Sesi.", "Choose a session from the Sessions list, then open Session Details."),
        ["analytics.tip.interpretation"] = ("Baca ringkasan sesi dulu sebelum melihat grafik per pemain.", "Read the session summary first before reviewing per-player charts."),
        ["analytics.tip.followup"] = ("Buka Rincian Sesi atau Rincian Pemain untuk investigasi metrik spesifik.", "Open Session Details or Player Details to investigate specific metrics."),
        ["analytics.tip.select_session"] = ("Pilih sesi dari daftar Sesi Permainan untuk melihat progres Anda.", "Choose a session from Game Sessions to view your progress."),
        ["analytics.tip.focus_score"] = ("Pantau arus kas bersih, poin kebutuhan, dan poin target tabungan.", "Track net cashflow, need points, and saving goal points."),
        ["analytics.tip.risk_control"] = ("Perhatikan penalti misi, penalti pinjaman, dan status pinjaman belum lunas.", "Watch mission penalties, loan penalties, and unpaid loan status."),
        ["analytics.players"] = ("Pemain", "Players"),
        ["analytics.chart.session_summary"] = ("Ringkasan Kinerja Sesi", "Session Performance Summary"),
        ["analytics.chart.cashflow_per_player"] = ("Arus Kas per Pemain", "Cashflow per Player"),
        ["analytics.chart.personal_cashflow"] = ("Arus Kas Pribadi", "Personal Cashflow"),
        ["analytics.chart.game_points"] = ("Poin Permainan", "Game Points"),
        ["analytics.chart.risk_control"] = ("Kontrol Risiko", "Risk Control"),
        ["analytics.chart.operations"] = ("Operasional dan Kepatuhan", "Operations and Compliance"),
        ["analytics.chart.cash_in"] = ("Kas Masuk", "Cash In"),
        ["analytics.chart.cash_out"] = ("Kas Keluar", "Cash Out"),
        ["analytics.chart.net"] = ("Bersih", "Net"),
        ["analytics.chart.value"] = ("Nilai", "Value"),
        ["analytics.chart.points"] = ("Poin", "Points"),
        ["analytics.chart.risk"] = ("Risiko", "Risk"),
        ["analytics.chart.summary"] = ("Ringkasan", "Summary"),
        ["analytics.chart.event"] = ("Aktivitas", "Event"),
        ["analytics.chart.unavailable"] = ("Grafik belum tersedia.", "Chart is not available yet."),
        ["analytics.chart.no_data"] = ("Belum ada data untuk ditampilkan.", "No data available to display."),
        ["analytics.error.invalid_session_id"] = ("ID Sesi tidak valid.", "Invalid Session ID."),
        ["analytics.error.session_not_available_for_player"] = ("Sesi tidak tersedia untuk akun pemain ini.", "This session is not available for this player account."),
        ["analytics.error.load_sessions_failed"] = ("Gagal memuat daftar sesi. Status: {status}", "Failed to load session list. Status: {status}"),
        ["analytics.error.invalid_sessions_response"] = ("Respons daftar sesi tidak valid.", "Invalid session list response."),
        ["analytics.error.load_session_analytics_failed"] = ("Gagal memuat analitika sesi. Status: {status}", "Failed to load session analytics. Status: {status}"),
        ["analytics.error.invalid_session_analytics_response"] = ("Respons analitika sesi tidak valid.", "Invalid session analytics response."),
        ["analytics.error.load_ruleset_analytics_failed"] = ("Gagal memuat analitika set aturan. Status: {status}", "Failed to load ruleset analytics. Status: {status}"),
        ["analytics.error.invalid_ruleset_analytics_response"] = ("Respons analitika set aturan tidak valid.", "Invalid ruleset analytics response."),

        ["sessions.management"] = ("Manajemen Sesi", "Session Management"),
        ["sessions.title"] = ("Daftar Sesi Permainan", "Game Session List"),
        ["sessions.subtitle"] = ("Pantau status sesi dan buka rincian analitika tiap sesi.", "Monitor session status and open analytics details for each session."),
        ["sessions.player_management"] = ("Sesi Pemain", "Player Sessions"),
        ["sessions.player_title"] = ("Daftar sesi saya", "My session list"),
        ["sessions.player_subtitle"] = ("Lihat sesi yang Anda ikuti dan buka Rincian progres permainan Anda.", "View sessions you joined and open your gameplay progress details."),
        ["sessions.readonly"] = ("Hanya Baca", "Read-only"),
        ["sessions.total_sessions"] = ("Total Sesi", "Total Sessions"),
        ["sessions.my_sessions"] = ("Sesi saya", "My sessions"),
        ["sessions.started"] = ("Sedang Berjalan", "In Progress"),
        ["sessions.ended"] = ("Sesi Selesai", "Completed Sessions"),
        ["sessions.tips.instructor.title"] = ("Tips penggunaan menu Sesi", "Sessions menu tips"),
        ["sessions.tips.player.title"] = ("Tips membaca sesi untuk pemain", "Player session tips"),
        ["sessions.step"] = ("Langkah", "Step"),
        ["sessions.tips.instructor.step1"] = ("Pilih sesi lalu klik Lihat Rincian Sesi.", "Choose a session, then click View Session Details."),
        ["sessions.tips.instructor.step2"] = ("Di halaman Rincian Sesi, aktifkan Set Aturan lewat tombol Ganti/Atur Set Aturan Aktif.", "On Session Details, activate the ruleset via Set or Change Active Ruleset."),
        ["sessions.tips.instructor.step3"] = ("Masuk ke Rincian Pemain untuk evaluasi metrik individual.", "Open Player Details to evaluate individual metrics."),
        ["sessions.tips.player.step1"] = ("Pilih sesi yang ingin ditinjau.", "Choose the session you want to review."),
        ["sessions.tips.player.step2"] = ("Buka Rincian Sesi untuk melihat ringkasan performa pribadi Anda.", "Open Session Details to view your personal performance summary."),
        ["sessions.tips.player.step3"] = ("Cek linimasa aktivitas agar keputusan per giliran lebih mudah dievaluasi.", "Check the event timeline so per-turn decisions are easier to evaluate."),
        ["sessions.legend.title"] = ("Arti status sesi", "Session status legend"),
        ["sessions.legend.started_hint"] = ("Sesi sedang berjalan.", "Session is currently running."),
        ["sessions.legend.created_hint"] = ("Sesi sudah dibuat, belum dimulai.", "Session has been created but not started."),
        ["sessions.legend.ended_hint"] = ("Sesi sudah selesai.", "Session has finished."),
        ["sessions.view_progress"] = ("Lihat Rincian Sesi", "View Session Details"),
        ["sessions.live_log"] = ("Log Sesi Real-time", "Real-time Session Log"),
        ["sessions.detail_title"] = ("Rincian dan Analitika Sesi", "Session Details and Analytics"),
        ["sessions.analytics_title"] = ("Analitika Sesi", "Session Analytics"),
        ["sessions.activate_ruleset"] = ("Ganti/Atur Set Aturan Aktif", "Set or Change Active Ruleset"),
        ["sessions.winner.title"] = ("Pemenang Sesi", "Session Winner"),
        ["sessions.winner.subtitle"] = ("Performa terbaik pada sesi ini", "Best performance in this session"),
        ["sessions.winner.net"] = ("Bersih Arus Kas", "Net cashflow"),
        ["sessions.winner.happiness"] = ("Kebahagiaan", "Happiness"),
        ["sessions.winner.cash_in"] = ("Kas Masuk", "Cash in"),
        ["sessions.champion.title"] = ("Juara Kategori Sesi", "Session Category Champions"),
        ["sessions.champion.subtitle"] = ("Dipisahkan menjadi juara peduli donasi dan juara dana pensiun.", "Separated into donation care and pension fund champions."),
        ["sessions.champion.donation"] = ("Juara Peduli Donasi", "Donation Care Champion"),
        ["sessions.champion.pension"] = ("Juara Dana Pensiun", "Pension Fund Champion"),
        ["sessions.champion.none"] = ("Belum ada data juara kategori untuk sesi ini.", "No category champion data for this session yet."),
        ["sessions.rank_label"] = ("Juara", "Champion"),
        ["sessions.active_ruleset.title"] = ("Set Aturan Aktif Sesi", "Session Active Ruleset"),
        ["sessions.active_ruleset.subtitle"] = ("Set Aturan ini menjadi acuan validasi aturan dan penilaian pada sesi ini.", "This ruleset is the source of rule validation and scoring in this session."),
        ["sessions.active_ruleset.empty"] = ("Belum ada Set Aturan aktif pada sesi ini.", "No active ruleset for this session yet."),
        ["sessions.ruleset_title"] = ("Pilih Set Aturan untuk Sesi Ini", "Select Ruleset for This Session"),
        ["sessions.ruleset_hint"] = ("Masukkan versi aturan (contoh: 1 atau versi terbaru).", "Enter ruleset version (for example: 1 or latest)."),
        ["sessions.activate"] = ("Aktifkan Aturan", "Activate Ruleset"),
        ["sessions.ruleset_guide"] = ("Panduan Aktivasi Set Aturan", "Ruleset Activation Guide"),
        ["sessions.ruleset_step1"] = ("Pilih set aturan yang akan dipakai.", "Choose the ruleset to use."),
        ["sessions.ruleset_step2"] = ("Pilih versi aturan yang ingin diaktifkan.", "Choose the ruleset version to activate."),
        ["sessions.note"] = ("Catatan", "Note"),
        ["sessions.ruleset_note"] = ("Pastikan versi berstatus AKTIF sebelum menyimpan.", "Ensure the version is ACTIVE before saving."),
        ["sessions.timeline"] = ("Linimasa", "Timeline"),
        ["sessions.timeline_title"] = ("Linimasa Aktivitas Sesi", "Session Activity Timeline"),
        ["sessions.timeline_subtitle"] = ("Urutan aktivitas berdasarkan waktu dan nomor urut aktivitas.", "Activity order based on timestamp and event sequence."),
        ["sessions.timeline_chart_progress"] = ("Diagram Aktivitas dari Awal hingga Selesai", "Event Timeline from Start to Finish"),
        ["sessions.timeline_chart_actor"] = ("Sebaran Aktivitas per Aktor terhadap Waktu", "Event Distribution by Actor Over Time"),
        ["sessions.timeline_seq"] = ("Urut", "Seq"),
        ["sessions.timeline_day_turn"] = ("Hari dan Giliran Terakhir", "Latest Day and Turn"),
        ["sessions.day_label"] = ("Hari", "Day"),
        ["sessions.turn_label"] = ("Giliran", "Turn"),
        ["sessions.activity_default"] = ("Detail aktivitas belum tersedia", "Activity details not available"),
        ["sessions.timeline_actor"] = ("Aktor Aktivitas Terakhir", "Latest Activity Actor"),
        ["sessions.timeline_flow"] = ("Alur", "Flow"),
        ["sessions.timeline_description"] = ("Penjelasan", "Description"),
        ["sessions.timeline_empty"] = ("Belum ada aktivitas linimasa pada sesi ini.", "No timeline events for this session yet."),
        ["sessions.timeline_chart_cumulative_events"] = ("Kumulatif Aktivitas", "Cumulative Events"),
        ["sessions.timeline_chart_event_sequence"] = ("Urutan aktivitas", "Event sequence order"),
        ["sessions.timeline_chart_minutes_since_first"] = ("Menit sejak aktivitas pertama", "Minutes since first event"),
        ["sessions.timeline_chart_event_count"] = ("Jumlah aktivitas (kumulatif)", "Event count (cumulative)"),
        ["sessions.timeline_chart_events_per_turn"] = ("Jumlah aktivitas per giliran", "Event count per turn"),
        ["sessions.timeline_chart_turn_number"] = ("Nomor giliran", "Turn number"),
        ["sessions.timeline_tooltip_minutes"] = ("+{value} menit", "+{value} min"),
        ["sessions.timeline_tooltip_event"] = ("Aktivitas #{event} | urut {seq} | {actor} | {action}", "Event #{event} | seq {seq} | {actor} | {action}"),
        ["sessions.timeline_tooltip_actor"] = ("{actor} | hari {day} ({weekday}) | giliran {turn} | urut {seq} | {action}", "{actor} | day {day} ({weekday}) | turn {turn} | seq {seq} | {action}"),
        ["sessions.timeline_actor_help"] = ("Kategori aktor di grafik: siapa yang memicu aktivitas selama sesi.", "Actor categories in the chart: who triggered events during the session."),
        ["sessions.journey.board_title"] = ("Jejak perjalanan permainan", "Board-style game journey"),
        ["sessions.journey.board_subtitle"] = ("Visual papan ini otomatis mengikuti urutan aktivitas terbaru yang masuk dari IDN/API.", "This board visual automatically follows the latest event order from IDN/API."),
        ["sessions.journey.last_sync"] = ("Sinkron Data Terakhir", "Last Data Sync"),
        ["sessions.journey.latest_activity"] = ("Aksi Terakhir", "Latest Action"),
        ["sessions.journey.graph_title"] = ("Grafik Interaktif Pergerakan IDN", "Interactive IDN Movement Graph"),
        ["sessions.journey.graph_subtitle"] = ("Klik titik grafik untuk menyorot pergerakan pemain pada papan jejak dan daftar aktivitas.", "Click chart points to highlight player movements on the journey board and activity feed."),
        ["sessions.journey.graph_unavailable"] = ("Grafik interaktif belum tersedia.", "Interactive graph is not available yet."),
        ["sessions.journey.graph_empty"] = ("Belum ada pergerakan untuk divisualkan pada grafik.", "No movements are available to visualize on the chart."),
        ["sessions.journey.graph_axis_seq"] = ("Urutan Aktivitas", "Event Sequence"),
        ["sessions.journey.graph_axis_order"] = ("Urutan Pergerakan", "Movement Order"),
        ["sessions.journey.no_events"] = ("Belum ada aktivitas untuk divisualkan.", "No events available to visualize yet."),
        ["sessions.journey.realtime_status"] = ("Gagal sinkron alur permainan (status {status}).", "Failed to sync gameplay journey (status {status})."),
        ["sessions.journey.realtime_network"] = ("Koneksi ke server terputus saat sinkron alur permainan.", "Connection to server was lost while syncing gameplay journey."),
        ["sessions.error.too_many_requests"] = ("Terlalu banyak permintaan ke API. Tunggu sebentar lalu coba lagi.", "Too many requests to the API. Please wait and try again."),
        ["sessions.error.load_sessions_failed"] = ("Gagal mengambil daftar sesi. Status: {status}", "Failed to fetch session list. Status: {status}"),
        ["sessions.error.load_timeline_failed"] = ("Gagal memuat alur aktivitas sesi. Status: {status}", "Failed to load session activity timeline. Status: {status}"),
        ["sessions.error.ruleset_version_required"] = ("Set aturan dan versinya wajib dipilih.", "Ruleset and version are required."),
        ["sessions.error.activate_ruleset_failed"] = ("Gagal mengaktifkan set aturan. Status: {status}", "Failed to activate ruleset. Status: {status}"),
        ["sessions.error.load_detail_failed"] = ("Gagal memuat rincian sesi. Status: {status}", "Failed to load session details. Status: {status}"),
        ["sessions.error.load_rulesets_failed"] = ("Gagal memuat set aturan. Status: {status}", "Failed to load rulesets. Status: {status}"),
        ["sessions.actor.player"] = ("Pemain", "Player"),
        ["sessions.actor.system"] = ("Sistem", "System"),
        ["sessions.actor.instructor"] = ("Instruktur", "Instructor"),
        ["sessions.actor.other"] = ("Lainnya", "Other"),
        ["sessions.actor.player.desc"] = ("Aksi yang dilakukan pemain selama permainan.", "Actions performed by players during gameplay."),
        ["sessions.actor.system.desc"] = ("Aktivitas otomatis dari sistem/mesin aturan.", "Automatic events generated by the system/rules engine."),
        ["sessions.actor.instructor.desc"] = ("Aktivitas yang dipicu instruktur (kontrol sesi).", "Events triggered by instructors (session controls)."),
        ["sessions.actor.other.desc"] = ("Aktivitas dengan tipe aktor di luar tiga kategori utama.", "Events with actor types outside the three primary categories."),

        ["players.management"] = ("Manajemen Pemain", "Player Management"),
        ["players.title"] = ("Direktori Pemain", "Player Directory"),
        ["players.subtitle"] = ("Daftar pemain untuk validasi identitas dan akses rincian performa.", "Player list for identity validation and access to performance details."),
        ["players.total_players"] = ("Total Pemain", "Total Players"),
        ["players.total_sessions"] = ("Total Sesi Diikuti", "Total Sessions Joined"),
        ["players.tips.title"] = ("Tips penggunaan menu Pemain", "Players menu tips"),
        ["players.tip_key.validate"] = ("Validasi", "Validation"),
        ["players.tip_key.tracking"] = ("Pelacakan", "Tracking"),
        ["players.tip_key.analysis"] = ("Analisis", "Analysis"),
        ["players.tip.validate"] = ("Pastikan nama pemain sesuai data sesi.", "Make sure player names match session data."),
        ["players.tip.tracking"] = ("Gunakan ID Pemain untuk melacak aktivitas dan transaksi di Rincian Pemain.", "Use Player ID to track activities and transactions in Player Details."),
        ["players.tip.analysis"] = ("Buka Rincian Pemain pada sesi yang dipilih untuk melihat metrik per sesi.", "Open Player Details in the selected session to view per-session metrics."),
        ["players.count_suffix"] = ("pemain", "players"),
        ["players.winner_badge"] = ("Juara 1", "Winner 1"),
        ["players.champion.donation_short"] = ("Donasi", "Donation"),
        ["players.champion.pension_short"] = ("Pensiun", "Pension"),
        ["players.add"] = ("Tambah", "Add"),
        ["players.name_placeholder"] = ("Nama pemain", "Player name"),
        ["players.detail_title"] = ("Rincian Pemain pada Sesi", "Player Session Details"),
        ["players.analytics_title"] = ("Analitika Pemain", "Player Analytics"),
        ["players.error.load_session_analytics_failed"] = ("Gagal memuat analitika sesi. Status: {status}", "Failed to load session analytics. Status: {status}"),
        ["players.error.load_transactions_failed"] = ("Gagal memuat transaksi. Status: {status}", "Failed to load transactions. Status: {status}"),
        ["players.error.load_gameplay_failed"] = ("Gagal memuat metrik permainan. Status: {status}", "Failed to load gameplay metrics. Status: {status}"),
        ["players.error.load_player_directory_failed"] = ("Gagal memuat daftar pemain. Status: {status}", "Failed to load player list. Status: {status}"),
        ["players.error.load_sessions_grouping_failed"] = ("Gagal memuat daftar sesi untuk pengelompokan pemain. Status: {status}", "Failed to load session list for player grouping. Status: {status}"),
        ["players.no_transactions"] = ("Belum ada transaksi.", "No transactions yet."),
        ["players.economy_snapshot"] = ("Ringkasan Ekonomi", "Economy Snapshot"),
        ["players.mission_risk"] = ("Misi dan Risiko", "Mission and Risk"),
        ["players.transaction_history"] = ("Riwayat Aktivitas Keuangan", "Financial Activity History"),
        ["players.cashflow_journey.badge"] = ("Alur Keuangan Pemain", "Player Cashflow Journey"),
        ["players.cashflow_journey.title"] = ("Statistik Alur Keuangan dari Awal sampai Akhir", "Cashflow Journey Statistics from Start to Finish"),
        ["players.cashflow_journey.subtitle"] = ("Ringkasan ini dimulai dari Kas Awal pemain, lalu mengikuti setiap transaksi hingga akhir sesi. Nilai Total Kas Masuk dan Total Kas Keluar adalah akumulasi sepanjang permainan, sehingga bisa mencapai ratusan meskipun saldo akhir lebih kecil.", "This summary starts from the player's Starting Cash, then follows every transaction to the end of the session. Total Cash In and Total Cash Out are cumulative across the game, so they can reach hundreds even when the ending balance is smaller."),
        ["players.cashflow_journey.starting_cash"] = ("Kas Awal Pemain", "Player Starting Cash"),
        ["players.cashflow_journey.ending_cash"] = ("Kas Akhir Pemain", "Player Ending Cash"),
        ["players.cashflow_journey.total_transactions"] = ("Total Transaksi", "Total Transactions"),
        ["players.cashflow_journey.total_in"] = ("Total Kas Masuk (Akumulasi)", "Total Cash In (Cumulative)"),
        ["players.cashflow_journey.total_out"] = ("Total Kas Keluar (Akumulasi)", "Total Cash Out (Cumulative)"),
        ["players.cashflow_journey.net"] = ("Arus Kas Bersih", "Net Cashflow"),
        ["players.cashflow_journey.running_peak"] = ("Puncak Saldo Berjalan", "Peak Running Balance"),
        ["players.cashflow_journey.running_lowest"] = ("Titik Terendah Saldo", "Lowest Balance Point"),
        ["players.cashflow_journey.period_start"] = ("Waktu Awal Periode", "Period Start Time"),
        ["players.cashflow_journey.period_end"] = ("Waktu Akhir Periode", "Period End Time"),
        ["players.cashflow_journey.in_count"] = ("Jumlah Transaksi Masuk", "Incoming Transaction Count"),
        ["players.cashflow_journey.out_count"] = ("Jumlah Transaksi Keluar", "Outgoing Transaction Count"),
        ["players.cashflow_journey.chart_title"] = ("Grafik Saldo Kas Berjalan per Transaksi", "Running Cash Balance per Transaction Chart"),
        ["players.cashflow_journey.series_name"] = ("Saldo Kas Berjalan", "Running Cash Balance"),
        ["players.cashflow_journey.formula"] = ("Saldo kumulatif = akumulasi IN dikurangi akumulasi OUT hingga titik transaksi ini.", "Cumulative balance = accumulated IN minus accumulated OUT up to this transaction point."),
        ["players.cashflow_journey.quick_check"] = ("Cek cepat saldo: Kas Awal {0} + Total Kas Masuk {1} - Total Kas Keluar {2} = Kas Akhir {3}.", "Quick balance check: Starting Cash {0} + Total Cash In {1} - Total Cash Out {2} = Ending Cash {3}."),
        ["players.cashflow_journey.empty"] = ("Belum ada data transaksi untuk pemain ini di sesi tersebut.", "No transaction data is available for this player in this session."),
        ["players.details.metric"] = ("Variabel", "Metric"),
        ["players.details.series"] = ("Seri", "Series"),
        ["players.details.transaction_label"] = ("Transaksi", "Transaction"),
        ["players.details.points_value"] = ("Poin/Nilai", "Points/Value"),
        ["players.details.metric_fallback"] = ("Metrik", "Metric"),
        ["players.details.item"] = ("Item", "Item"),
        ["players.details.combined_snapshot"] = ("Ringkasan Gabungan", "Combined Snapshot"),
        ["players.details.source_calc_label"] = ("Asal Data & Cara Hitung", "Data Source & Calculation"),
        ["players.details.source_calc_template"] = ("Asal data: {0}. Cara hitung: {1}", "Source: {0}. Calculation: {1}"),
        ["players.details.source_calc_default"] = ("Asal data: agregasi event sesi tervalidasi. Cara hitung: nilai mengikuti formula pada ruleset aktif.", "Source: validated session-event aggregation. Calculation: value follows formulas in the active ruleset."),
        ["players.details.source_raw_summary"] = ("Asal data: agregasi event sesi. Cara hitung: nilai diringkas dari transaksi/aksi pada domain ini.", "Source: session-event aggregation. Calculation: value is summarized from transactions/actions in this domain."),
        ["players.details.source_derived_summary"] = ("Asal data: agregasi event sesi tervalidasi. Cara hitung: nilai turunan mengikuti formula pada ruleset aktif.", "Source: validated session-event aggregation. Calculation: derived value follows formulas from the active ruleset."),
        ["players.details.source_line_raw_template"] = ("Asal data: {0}. Cara hitung: nilai mengikuti agregasi event sesi pada domain ini.", "Source: {0}. Calculation: value follows session-event aggregation in this domain."),
        ["players.details.source_line_derived_template"] = ("Asal data: {0}. Cara hitung: nilai turunan dihitung dari variabel mentah sesuai ruleset aktif.", "Source: {0}. Calculation: derived value is computed from raw variables based on the active ruleset."),
        ["players.details.selected_detail"] = ("Detail data terpilih", "Selected data details"),
        ["players.details.tap_hint"] = ("Ketuk batang atau titik pada diagram untuk melihat detail variabel, asal data, dan cara hitung.", "Tap bars or points in the chart to view metric details, data source, and calculation."),
        ["players.details.no_series"] = ("Belum ada rangkaian metrik untuk ditampilkan.", "No serial metrics are available to display."),
        ["players.details.no_points"] = ("Belum ada titik numerik untuk ditampilkan.", "No numeric points are available to display."),
        ["players.details.invalid_payload"] = ("Payload diagram tidak valid.", "Chart payload is invalid."),
        ["players.details.transaction.opening_cash"] = ("Kas Awal", "Opening Cash"),
        ["players.details.transaction.opening_cash_with_amount"] = ("Kas Awal ({0})", "Opening Cash ({0})"),
        ["players.details.transaction.cash_in"] = ("Kas Masuk", "Cash In"),
        ["players.details.transaction.cash_out"] = ("Kas Keluar", "Cash Out"),
        ["players.details.transaction.category.donation"] = ("Donasi", "Donation"),
        ["players.details.transaction.category.gold_trade"] = ("Transaksi Emas", "Gold Trade"),
        ["players.details.transaction.category.ingredient"] = ("Pembelian Bahan", "Ingredient Purchase"),
        ["players.details.transaction.category.order"] = ("Pesanan Makanan", "Meal Order"),
        ["players.details.transaction.category.freelance"] = ("Pekerjaan Freelance", "Freelance Work"),
        ["players.details.transaction.category.need_primary"] = ("Kebutuhan Primer", "Primary Need"),
        ["players.details.transaction.category.need_secondary"] = ("Kebutuhan Sekunder", "Secondary Need"),
        ["players.details.transaction.category.need_tertiary"] = ("Kebutuhan Tersier", "Tertiary Need"),
        ["players.details.transaction.category.saving_deposit"] = ("Setoran Tabungan", "Saving Deposit"),
        ["players.details.transaction.category.saving_withdraw"] = ("Penarikan Tabungan", "Saving Withdrawal"),
        ["players.details.transaction.category.risk_life"] = ("Dampak Risiko Kehidupan", "Life Risk Impact"),
        ["players.details.transaction.category.loan_taken"] = ("Pinjaman Diambil", "Loan Taken"),
        ["players.details.transaction.category.loan_repaid"] = ("Pelunasan Pinjaman", "Loan Repaid"),
        ["players.details.transaction.category.insurance_premium"] = ("Premi Asuransi", "Insurance Premium"),
        ["players.details.transaction.category.insurance_claim"] = ("Klaim Asuransi", "Insurance Claim"),
        ["players.details.transaction.category.emergency_option"] = ("Pilihan Kondisi Darurat", "Emergency Option"),
        ["players.details.formula.coins_net_end"] = ("Koin Awal + Total Kas Masuk - Total Kas Keluar.", "Starting Coins + Total Cash In - Total Cash Out."),
        ["players.details.formula.raw.cash_in_sum"] = ("Menjumlahkan semua transaksi kas masuk pemain pada domain ini.", "Sums all player cash-in transactions in this domain."),
        ["players.details.formula.raw.cash_out_sum"] = ("Menjumlahkan semua transaksi kas keluar pemain pada domain ini.", "Sums all player cash-out transactions in this domain."),
        ["players.details.formula.raw.per_turn_aggregate"] = ("Agregasi nilai per giliran berdasarkan transaksi/aksi yang tercatat pada giliran tersebut.", "Per-turn aggregation based on transactions/actions recorded in that turn."),
        ["players.details.formula.raw.direct_aggregate"] = ("Nilai diambil langsung dari agregasi event sesi pada domain ini.", "Value is read directly from session-event aggregation in this domain."),
        ["players.details.formula.derived.happiness_points"] = ("Poin Kebutuhan + Bonus + Poin Donasi + Poin Emas + Poin Pensiun + Poin Target Tabungan - Penalti Misi - Penalti Pinjaman", "Need Points + Bonus + Donation Points + Gold Points + Pension Points + Saving Goal Points - Mission Penalty - Loan Penalty"),
        ["players.details.formula.derived.net_cashflow"] = ("Total Kas Masuk - Total Kas Keluar.", "Total Cash In - Total Cash Out."),
        ["players.details.formula.derived.donation_points"] = ("Total Donasi x bobot poin donasi (set aturan aktif)", "Total Donations x donation-point weight (active ruleset)"),
        ["players.details.formula.derived.pension_points"] = ("Akumulasi dana pensiun akhir x bobot poin pensiun (set aturan aktif)", "End-game pension accumulation x pension-point weight (active ruleset)"),
        ["players.details.formula.derived.saving_goal_points"] = ("Pencapaian target tabungan x bobot poin target tabungan (set aturan aktif)", "Saving-goal achievement x saving-goal point weight (active ruleset)"),
        ["players.details.formula.derived.need_points"] = ("Akumulasi poin kartu kebutuhan sesuai aturan sesi", "Accumulated need-card points based on session rules"),
        ["players.details.formula.derived.penalty"] = ("Akumulasi penalti dari pelanggaran/ketidakpatuhan selama sesi", "Accumulated penalties from violations/non-compliance during the session"),
        ["players.details.formula.derived.points_weight"] = ("Poin dihitung sesuai bobot pada set aturan aktif", "Points are calculated using weights from the active ruleset"),
        ["players.details.formula.derived.default"] = ("Nilai turunan dihitung dari variabel mentah sesuai aturan pada ruleset aktif.", "Derived value is calculated from raw variables using formulas in the active ruleset."),
        ["players.details.raw_title"] = ("Variabel Permainan Fisik", "Physical Gameplay Variables"),
        ["players.details.raw_subtitle"] = ("Semua domain variabel mentah divisualkan sebagai diagram. Ringkasan gabungan tampil sebagai batang, metrik sisanya tetap dalam garis agar pola tetap mudah dibaca. Arahkan kursor atau ketuk batang/titik untuk melihat asal data, cara hitung, dan nilai poin/angka.", "All raw-variable domains are visualized as charts. Combined snapshots are shown as bars, while the remaining metrics stay as lines for readability. Hover over or tap each bar/point to see the data source, calculation, and point/value."),
        ["players.details.derived_title"] = ("Metrik Turunan Analitika", "Derived Analytics Metrics"),
        ["players.details.derived_subtitle"] = ("Metrik turunan disajikan per domain: ringkasan gabungan dalam batang, lalu detail tetap dalam garis agar tren dan perbandingan sama-sama jelas. Arahkan kursor atau ketuk batang/titik untuk melihat asal data, cara hitung, dan nilai poin/angka.", "Derived metrics are presented per domain: combined snapshots in bars, then details in lines so trends and comparisons stay clear. Hover over or tap each bar/point to see the data source, calculation, and point/value."),
        ["players.details.chart_count_suffix"] = ("diagram", "charts"),
        ["players.details.chart_domain_empty"] = ("Belum ada titik numerik untuk divisualkan pada domain ini.", "No numeric points are currently available for this domain."),
        ["players.details.chart_scroll_region"] = ("Rincian diagram dapat digeser secara horizontal", "Detailed charts can be scrolled horizontally"),
        ["players.details.chart_scroll_hint"] = ("Geser ke samping jika daftar diagram melebihi lebar panel.", "Scroll sideways if the chart list exceeds the panel width."),
        ["players.details.raw.coin_finance.title"] = ("Variabel Koin dan Finansial", "Coin and Financial Variables"),
        ["players.details.raw.coin_finance.desc"] = ("Modal awal, arus kas, donasi, tabungan, dan saldo akhir.", "Starting capital, cashflow, donations, savings, and end balance."),
        ["players.details.raw.ingredients.title"] = ("Variabel Kartu Bahan", "Ingredient Card Variables"),
        ["players.details.raw.ingredients.desc"] = ("Perolehan, stok, penggunaan, dan pemborosan bahan.", "Ingredient acquisition, stock, usage, and waste."),
        ["players.details.raw.meal_orders.title"] = ("Variabel Pesanan Makanan", "Meal Order Variables"),
        ["players.details.raw.meal_orders.desc"] = ("Jumlah pesanan, pendapatan pesanan, dan keputusan melewati pesanan.", "Order count, order income, and pass decisions."),
        ["players.details.raw.needs.title"] = ("Variabel Kartu Kebutuhan", "Need Card Variables"),
        ["players.details.raw.needs.desc"] = ("Kepemilikan kebutuhan primer-sekunder-tersier dan status misi koleksi.", "Primary-secondary-tertiary needs ownership and collection mission status."),
        ["players.details.raw.donations.title"] = ("Variabel Donasi", "Donation Variables"),
        ["players.details.raw.donations.desc"] = ("Nominal donasi, ranking donasi, dan poin donasi.", "Donation amount, donation rank, and donation points."),
        ["players.details.raw.gold.title"] = ("Variabel Investasi Emas", "Gold Investment Variables"),
        ["players.details.raw.gold.desc"] = ("Pembelian, penjualan, posisi akhir, dan arus kas emas.", "Gold buy/sell, ending position, and gold cashflow."),
        ["players.details.raw.pension.title"] = ("Variabel Dana Pensiun", "Pension Fund Variables"),
        ["players.details.raw.pension.desc"] = ("Komponen dana pensiun akhir dan peringkat poin pensiun.", "End-game pension components and pension ranking points."),
        ["players.details.raw.life_risk.title"] = ("Variabel Risiko Hidup", "Life Risk Variables"),
        ["players.details.raw.life_risk.desc"] = ("Frekuensi risiko, biaya risiko, dan mitigasi asuransi.", "Risk frequency, risk costs, and insurance mitigation."),
        ["players.details.raw.financial_goals.title"] = ("Variabel Target Finansial", "Financial Goal Variables"),
        ["players.details.raw.financial_goals.desc"] = ("Progres target finansial, pinjaman, dan status pelunasan.", "Financial goal progress, loans, and repayment status."),
        ["players.details.raw.actions.title"] = ("Variabel Penggunaan Token Aksi", "Action Token Usage Variables"),
        ["players.details.raw.actions.desc"] = ("Distribusi aksi per giliran, repetisi aksi, dan aksi terlewati.", "Per-turn action distribution, repetitions, and skipped actions."),
        ["players.details.raw.turns.title"] = ("Variabel Progres Giliran", "Turn-by-Turn Progression Variables"),
        ["players.details.raw.turns.desc"] = ("Perkembangan ekonomi dari awal sampai akhir permainan.", "Economic progression from start to end of the game."),
        ["players.details.derived.financial.title"] = ("Metrik Performa Finansial", "Financial Performance Metrics"),
        ["players.details.derived.financial.desc"] = ("Indeks kekayaan, diversifikasi pendapatan, efisiensi pengeluaran, dan margin laba.", "Net worth index, income diversification, spending efficiency, and profit margin."),
        ["players.details.derived.strategy.title"] = ("Metrik Keputusan Strategis", "Strategic Decision Metrics"),
        ["players.details.derived.strategy.desc"] = ("Selera risiko, leverage utang, dan ambisi target finansial.", "Risk appetite, debt leverage, and financial goal ambition."),
        ["players.details.derived.behavior.title"] = ("Metrik Perilaku Pemain", "Player Behavior Metrics"),
        ["players.details.derived.behavior.desc"] = ("Efisiensi aksi, keberhasilan pesanan, dan orientasi perencanaan.", "Action efficiency, order success, and planning orientation."),
        ["players.details.derived.flourishing.title"] = ("Metrik Flourishing", "Flourishing-Related Metrics"),
        ["players.details.derived.flourishing.desc"] = ("Keberagaman pemenuhan, komitmen donasi, dan komposisi portofolio kebahagiaan.", "Fulfillment diversity, donation commitment, and happiness portfolio composition."),
        ["players.gameplay_metrics"] = ("Metrik Permainan", "Gameplay Metrics"),
        ["players.gameplay_all_fields"] = ("Tampilkan Semua Field Metrik", "Show All Metric Fields"),
        ["players.player_focus_badge"] = ("Untuk Pemain", "For Players"),
        ["players.player_focus_title"] = ("Ringkasan cepat untuk keputusan berikutnya", "Quick snapshot for your next decisions"),
        ["players.player_focus_desc"] = ("Panel ini menampilkan metrik inti agar pemain cepat membaca progres ekonomi, strategi, dan perilaku.", "These panels highlight core metrics so players can quickly read economic, strategy, and behavior progress."),
        ["players.analytics_focus_badge"] = ("Untuk Analitika", "For Analytics"),
        ["players.analytics_focus_title"] = ("Peta metrik lengkap per domain", "Complete metric map by domain"),
        ["players.analytics_focus_desc"] = ("Semua field metrik tetap tersedia, tetapi dipisah per domain raw dan derived supaya audit lebih cepat.", "All metric fields remain available, but split by raw and derived domains for faster audits."),
        ["players.fusion_title"] = ("Ringkasan & peta metrik terpadu per domain", "Integrated summary and metric map by domain"),
        ["players.fusion_desc"] = ("Setiap domain menggabungkan sinyal cepat untuk keputusan pemain dan rincian field raw + turunan untuk audit analitika.", "Each domain combines quick decision signals with full raw + derived fields for analytics audits."),
        ["players.fusion.finance_desc"] = ("Fokus pada arus kas, efisiensi bisnis, dan akumulasi aset.", "Focus on cashflow, business efficiency, and asset accumulation."),
        ["players.fusion.strategy_desc"] = ("Fokus pada eksekusi aksi, perencanaan, dan kualitas pemenuhan kebutuhan.", "Focus on action execution, planning, and fulfillment quality."),
        ["players.fusion.risk_desc"] = ("Fokus pada risiko, komitmen pinjaman, dan disiplin misi.", "Focus on risk, loan commitments, and mission discipline."),
        ["players.fusion.raw_details"] = ("Detail Variabel Mentah", "Raw Variable Details"),
        ["players.fusion.derived_details"] = ("Detail Metrik Turunan", "Derived Metric Details"),
        ["players.metrics_raw_desc"] = ("Variabel mentah dibagi per domain agar jejak data permainan lebih mudah ditelusuri.", "Raw variables are grouped by domain so gameplay data trails are easier to trace."),
        ["players.metrics_derived_desc"] = ("Metrik turunan dan komponennya dikelompokkan agar interpretasi analitika lebih terarah.", "Derived metrics and their components are grouped for clearer analytics interpretation."),
        ["players.metric_items_suffix"] = ("item", "items"),
        ["players.financial_performance"] = ("Performa Finansial", "Financial Performance"),
        ["players.strategy_execution"] = ("Strategi & Eksekusi", "Strategy & Execution"),
        ["players.behavior_signals"] = ("Sinyal Perilaku", "Behavior Signals"),
        ["players.group.summary"] = ("Ringkasan Utama", "Main Summary"),
        ["players.group.coins"] = ("Koin dan Arus Kas", "Coins and Cashflow"),
        ["players.group.ingredients"] = ("Bahan", "Ingredients"),
        ["players.group.meal_orders"] = ("Pesanan Makanan", "Meal Orders"),
        ["players.group.needs"] = ("Kebutuhan", "Needs"),
        ["players.group.donations"] = ("Donasi", "Donations"),
        ["players.group.gold"] = ("Investasi Emas", "Gold Investment"),
        ["players.group.pension"] = ("Dana Pensiun", "Pension Fund"),
        ["players.group.life_risk"] = ("Risiko Hidup", "Life Risk"),
        ["players.group.financial_goals"] = ("Target Finansial", "Financial Goals"),
        ["players.group.actions"] = ("Aksi", "Actions"),
        ["players.group.turns"] = ("Progres Giliran", "Turn Progress"),
        ["players.group.notes"] = ("Catatan Sistem", "System Notes"),
        ["players.group.expense_components"] = ("Komponen Efisiensi Pengeluaran", "Expense Efficiency Components"),
        ["players.group.risk_components"] = ("Komponen Selera Risiko", "Risk Appetite Components"),
        ["players.group.happiness_portfolio"] = ("Portofolio Poin Kebahagiaan", "Happiness Points Portfolio"),
        ["players.metric.net_worth_index"] = ("Indeks Kekayaan Bersih", "Net Worth Index"),
        ["players.metric.income_diversification"] = ("Diversifikasi Pendapatan", "Income Diversification"),
        ["players.metric.expense_efficiency"] = ("Efisiensi Pengeluaran", "Expense Efficiency"),
        ["players.metric.business_profit_margin"] = ("Margin Laba Bisnis", "Business Profit Margin"),
        ["players.metric.growth_pattern_ratio"] = ("Rasio Pola Pertumbuhan", "Growth Pattern Ratio"),
        ["players.metric.risk_appetite"] = ("Selera Risiko (0-100)", "Risk Appetite (0-100)"),
        ["players.metric.debt_leverage"] = ("Leverage Utang", "Debt Leverage"),
        ["players.metric.goal_setting_ambition"] = ("Ambisi Penetapan Target", "Goal Setting Ambition"),
        ["players.metric.meal_order_success"] = ("Keberhasilan Pesanan Makanan", "Meal Order Success"),
        ["players.metric.action_efficiency"] = ("Efisiensi Aksi", "Action Efficiency"),
        ["players.metric.planning_horizon"] = ("Cakrawala Perencanaan", "Planning Horizon"),
        ["players.metric.donation_aggressiveness"] = ("Agresivitas Donasi", "Donation Aggressiveness"),
        ["players.metric.donation_stability"] = ("Stabilitas Donasi (StdDev)", "Donation Stability (StdDev)"),
        ["players.metric.business_efficiency_ratio"] = ("Rasio Efisiensi Bisnis", "Business Efficiency Ratio"),
        ["players.metric.gold_roi"] = ("ROI Emas", "Gold ROI"),
        ["players.metric.mission_achievement"] = ("Pencapaian Misi", "Mission Achievement"),
        ["players.metric.fulfillment_diversity"] = ("Keberagaman Pemenuhan", "Fulfillment Diversity"),
        ["players.metric.donation_commitment"] = ("Komitmen Donasi", "Donation Commitment"),
        ["players.metric.debt_ratio"] = ("Rasio Utang", "Debt Ratio"),
        ["players.metric.risk_exposure"] = ("Eksposur Risiko", "Risk Exposure"),
        ["players.metric.risk_mitigation"] = ("Mitigasi Risiko", "Risk Mitigation"),
        ["players.metric.loan_repayment_discipline"] = ("Disiplin Pelunasan Pinjaman", "Loan Repayment Discipline"),
        ["players.metric.basic_need_profile"] = ("Profil Kebutuhan Dasar", "Basic Need Profile"),
        ["players.metric.collector_need_profile"] = ("Profil Kebutuhan Kolektor", "Collector Need Profile"),
        ["players.metric.specialist_need_profile"] = ("Profil Kebutuhan Spesialis", "Specialist Need Profile"),
        ["players.raw.economy"] = ("Ekonomi", "Economy"),
        ["players.raw.activity"] = ("Aktivitas", "Activity"),
        ["players.raw.commitment"] = ("Komitmen", "Commitment"),
        ["players.raw.starting_coins"] = ("Koin Awal", "Starting Coins"),
        ["players.raw.coins_held_current"] = ("Koin Saat Ini", "Coins Held (Current)"),
        ["players.raw.coins_saved"] = ("Koin Ditabung", "Coins Saved"),
        ["players.raw.coins_donated"] = ("Koin Donasi", "Coins Donated"),
        ["players.raw.coins_net_end"] = ("Koin Bersih Akhir Permainan", "Coins Net End Game"),
        ["players.raw.coins_net_end_game"] = ("Koin Bersih Akhir Permainan", "Coins Net End Game"),
        ["players.raw.meal_order_income_total"] = ("Total Pendapatan Pesanan", "Meal Order Income Total"),
        ["players.raw.ingredients_collected"] = ("Bahan Terkumpul", "Ingredients Collected"),
        ["players.raw.ingredients_held_current"] = ("Bahan Tersimpan Saat Ini", "Ingredients Held (Current)"),
        ["players.raw.ingredients_wasted"] = ("Bahan Terbuang", "Ingredients Wasted"),
        ["players.raw.meal_orders_claimed"] = ("Pesanan Diklaim", "Meal Orders Claimed"),
        ["players.raw.meal_orders_passed"] = ("Pesanan Dilewati", "Meal Orders Passed"),
        ["players.raw.need_cards_purchased"] = ("Kartu Kebutuhan Dibeli", "Need Cards Purchased"),
        ["players.raw.needs_breakdown"] = ("Primer / Sekunder / Tersier", "Primary / Secondary / Tertiary Needs"),
        ["players.raw.gold_cards_held_end"] = ("Kartu Emas Tersisa", "Gold Cards Held End"),
        ["players.raw.actions_skipped"] = ("Aksi Dilewati", "Actions Skipped"),
        ["players.raw.loans_taken"] = ("Pinjaman Diambil", "Loans Taken"),
        ["players.raw.loans_repaid"] = ("Pinjaman Dibayar", "Loans Repaid"),
        ["players.raw.loans_unpaid_end"] = ("Pinjaman Belum Lunas", "Loans Unpaid End"),
        ["players.raw.collection_mission_complete"] = ("Misi Koleksi Selesai", "Collection Mission Complete"),

        ["rulesets.management"] = ("Manajemen Set Aturan", "Ruleset Management"),
        ["rulesets.title"] = ("Daftar Set Aturan Permainan", "Game Ruleset List"),
        ["rulesets.subtitle"] = ("Kelola aturan setup, alur aksi, dan scoring sesi.", "Manage setup rules, action flow, and session scoring."),
        ["rulesets.total_rulesets"] = ("Total Set Aturan", "Total rulesets"),
        ["rulesets.unified_subtitle"] = ("Buat Set Aturan baru, cek historinya, lalu aktifkan versi yang tepat sebelum sesi dimulai.", "Create new rulesets, review history, then activate the correct version before a session starts."),
        ["rulesets.quick_tools"] = ("Pencarian dan Aksi Cepat", "Search and Quick Actions"),
        ["rulesets.search"] = ("Cari Set Aturan", "Search Rulesets"),
        ["rulesets.search_placeholder"] = ("Cari nama, ID, atau versi ruleset...", "Search ruleset name, ID, or version..."),
        ["rulesets.sort"] = ("Urutkan", "Sort"),
        ["rulesets.sort.name_asc"] = ("Nama A-Z", "Name A-Z"),
        ["rulesets.sort.name_desc"] = ("Nama Z-A", "Name Z-A"),
        ["rulesets.sort.version_desc"] = ("Versi tertinggi", "Highest version"),
        ["rulesets.sort.version_asc"] = ("Versi terendah", "Lowest version"),
        ["rulesets.page_size"] = ("Baris per Halaman", "Rows per Page"),
        ["rulesets.clear_filter"] = ("Reset", "Reset"),
        ["rulesets.no_filtered"] = ("Tidak ada set aturan yang cocok dengan filter.", "No rulesets match the filter."),
        ["rulesets.select"] = ("Pilih", "Select"),
        ["rulesets.select_all"] = ("Pilih semua baris di halaman ini", "Select all rows on this page"),
        ["rulesets.select_one"] = ("Pilih set aturan ini", "Select this ruleset"),
        ["rulesets.selected"] = ("Dipilih", "Selected"),
        ["rulesets.bulk_delete"] = ("Hapus Terpilih", "Delete Selected"),
        ["rulesets.bulk_delete_confirm"] = ("Hapus semua set aturan terpilih?", "Delete all selected rulesets?"),
        ["rulesets.pagination_prev"] = ("Sebelumnya", "Previous"),
        ["rulesets.pagination_next"] = ("Berikutnya", "Next"),
        ["rulesets.tips.title"] = ("Tips penggunaan menu Set Aturan", "Rulesets menu tips"),
        ["rulesets.tips.form_title"] = ("Tips mengisi Set Aturan", "Ruleset form tips"),
        ["rulesets.tip.create"] = ("Siapkan Set Aturan sesuai mode sesi.", "Prepare rulesets based on the session mode."),
        ["rulesets.tip.versioning"] = ("Aktifkan versi valid sebelum sesi dimulai.", "Activate a valid version before the session starts."),
        ["rulesets.tip.safety"] = ("Hapus Set Aturan yang sudah tidak dipakai.", "Delete rulesets that are no longer used."),
        ["rulesets.legend.title"] = ("Arti status versi aturan", "Ruleset version status legend"),
        ["rulesets.legend.active_hint"] = ("Versi aktif yang sedang dipakai.", "Active version currently in use."),
        ["rulesets.legend.draft_hint"] = ("Versi draf, belum dijadikan aktif.", "Draft version, not active yet."),
        ["rulesets.legend.retired_hint"] = ("Versi lama yang sudah tidak aktif.", "Older version that is no longer active."),
        ["rulesets.tip.versioning_draft"] = ("Atur draf terlebih dahulu, lalu aktifkan versinya.", "Prepare the draft first, then activate its version."),
        ["rulesets.tip.consistency"] = ("Isi formulir, lalu sistem membuat JSON secara otomatis.", "Fill in the form, then let the system generate JSON automatically."),
        ["rulesets.tip.safety_before_start"] = ("Lakukan perubahan Set Aturan sebelum sesi dimulai.", "Apply ruleset changes before the session starts."),
        ["rulesets.create"] = ("Buat Set Aturan Baru", "Create New Ruleset"),
        ["rulesets.create_title"] = ("Buat Set Aturan baru", "Create new ruleset"),
        ["rulesets.create_subtitle"] = ("Isi form aturan permainan. JSON konfigurasi dibuat otomatis.", "Fill the gameplay rules form. Configuration JSON is generated automatically."),
        ["rulesets.edit"] = ("Edit aturan", "Edit rules"),
        ["rulesets.duplicate"] = ("Duplikat", "Duplicate"),
        ["rulesets.copy_suffix"] = ("(Salinan)", "(Copy)"),
        ["rulesets.edit_title"] = ("Edit aturan Set Aturan", "Edit ruleset rules"),
        ["rulesets.edit_subtitle"] = ("Perbarui aturan untuk membuat versi baru tanpa mengubah riwayat versi lama.", "Update rules to create a new version without changing previous version history."),
        ["rulesets.quick_guide_title"] = ("Panduan cepat mengisi Set Aturan", "Quick guide to filling a ruleset"),
        ["rulesets.quick_guide_beginner"] = ("Mode PEMULA: rekomendasi kas awal 20, fitur pinjaman/asuransi/tabungan nonaktif.", "BEGINNER mode: recommended starting cash 20, with loan/insurance/saving features disabled."),
        ["rulesets.quick_guide_advanced"] = ("Mode MAHIR: rekomendasi kas awal 10, fitur pinjaman/asuransi/tabungan aktif.", "ADVANCED mode: recommended starting cash 10, with loan/insurance/saving features enabled."),
        ["rulesets.quick_guide_activation"] = ("Setelah menyimpan, aktifkan versi ruleset di sesi agar aturan ini benar-benar dipakai.", "After saving, activate the ruleset version in a session so these rules are actually applied."),
        ["rulesets.detail_title"] = ("Rincian Set Aturan", "Ruleset details"),
        ["rulesets.readonly_hint"] = ("Mode baca saja.", "Read-only mode."),
        ["rulesets.back_to_list"] = ("Kembali ke daftar", "Back to list"),
        ["rulesets.delete"] = ("Hapus", "Delete"),
        ["rulesets.save"] = ("Simpan Set Aturan", "Save Ruleset"),
        ["rulesets.update"] = ("Simpan Versi Baru", "Save New Version"),
        ["rulesets.analytics_link"] = ("Analitika Set Aturan", "Ruleset Analytics"),
        ["rulesets.total_versions"] = ("Total Versi", "Total Versions"),
        ["rulesets.active_versions"] = ("Versi Aktif", "Active Versions"),
        ["rulesets.status_label"] = ("Status Set Aturan", "Ruleset Status"),
        ["rulesets.status.available"] = ("Tersedia", "Available"),
        ["rulesets.config_summary"] = ("Ringkasan Konfigurasi Aturan", "Ruleset Configuration Summary"),
        ["rulesets.config_unavailable"] = ("Konfigurasi belum tersedia.", "Configuration is not available yet."),
        ["rulesets.version_history"] = ("Riwayat Versi Aturan", "Ruleset Version History"),
        ["rulesets.default_components.title"] = ("Komponen Default (Pemula + Mahir)", "Default Components (Beginner + Advanced)"),
        ["rulesets.default_components.subtitle"] = ("Daftar ruleset bawaan berisi susunan komponen permainan.", "List of built-in rulesets containing gameplay component setup."),
        ["rulesets.default_components.empty"] = ("Belum ada ruleset default komponen yang tersedia.", "No default component rulesets are available yet."),
        ["rulesets.default_components.open_detail"] = ("Lihat komponen", "View components"),
        ["rulesets.components.title"] = ("Katalog Komponen Ruleset", "Ruleset Component Catalog"),
        ["rulesets.components.subtitle"] = ("Data ini diambil dari endpoint komponen ruleset sesuai versi aktif/terbaru.", "This data is fetched from the ruleset component endpoint for active/latest version."),
        ["rulesets.components.unavailable"] = ("Katalog komponen belum tersedia untuk ruleset ini.", "Component catalog is not available for this ruleset yet."),
        ["rulesets.components.ruleset_version_id"] = ("ID Versi Set Aturan", "Ruleset Version ID"),
        ["rulesets.components.item_count"] = ("Jumlah Item Komponen", "Total Component Items"),
        ["rulesets.components.empty"] = ("Belum ada item komponen yang dapat ditampilkan.", "No component items are available to display."),
        ["rulesets.components.raw_json"] = ("Lihat JSON mentah komponen", "View raw component JSON"),
        ["rulesets.set_active"] = ("Jadikan Aktif", "Set as Active"),
        ["rulesets.delete_version"] = ("Hapus Versi", "Delete Version"),
        ["rulesets.delete_version_confirm"] = ("Hapus versi ini dari riwayat?", "Delete this version from history?"),
        ["rulesets.delete_version_success"] = ("Versi {version} berhasil dihapus.", "Version {version} was deleted successfully."),
        ["rulesets.form.core_setup"] = ("Aturan Dasar Sesi", "Session Core Rules"),
        ["rulesets.form.mode"] = ("Mode", "Mode"),
        ["rulesets.form.mode_beginner"] = ("PEMULA", "BEGINNER"),
        ["rulesets.form.mode_advanced"] = ("MAHIR", "ADVANCED"),
        ["rulesets.form.actions_per_turn"] = ("Jumlah Aksi per Giliran", "Actions per Turn"),
        ["rulesets.form.starting_cash"] = ("Kas Awal per Pemain", "Starting Cash per Player"),
        ["rulesets.form.player_ordering"] = ("Urutan Pemain", "Player Ordering"),
        ["rulesets.form.player_ordering_join_order"] = ("Urutan Bergabung (Sesi)", "Join Order (Session)"),
        ["rulesets.form.player_ordering_event_sequence"] = ("Aktivitas Pertama", "First Event"),
        ["rulesets.form.player_ordering_player_id"] = ("ID Pemain", "Player ID"),
        ["rulesets.form.player_ordering_username"] = ("Username (A-Z)", "Username (A-Z)"),
        ["rulesets.form.freelance_income"] = ("Pendapatan Kerja Lepas", "Freelance Income"),
        ["rulesets.form.weekday_features"] = ("Fitur Hari", "Weekday Features"),
        ["rulesets.form.friday_donation"] = ("Donasi Jumat", "Friday Donation"),
        ["rulesets.form.saturday_gold_trade"] = ("Perdagangan Emas Sabtu", "Saturday Gold Trade"),
        ["rulesets.form.sunday_rest"] = ("Minggu Libur", "Sunday Rest"),
        ["rulesets.form.constraints"] = ("Batasan", "Constraints"),
        ["rulesets.form.cash_min"] = ("Kas Minimum", "Cash Min"),
        ["rulesets.form.max_ingredient_total"] = ("Total Bahan Maksimum", "Max Ingredient Total"),
        ["rulesets.form.max_same_ingredient"] = ("Batas Bahan Sejenis", "Max Same Ingredient"),
        ["rulesets.form.primary_need_max_day"] = ("Batas Kebutuhan Primer / Hari", "Primary Need Max / Day"),
        ["rulesets.form.require_primary_first"] = ("Wajib Primer sebelum Lainnya", "Require Primary Before Others"),
        ["rulesets.form.economy_advanced"] = ("Ekonomi, Donasi, dan Fitur Mahir", "Economy, Donation, and Advanced Features"),
        ["rulesets.form.donation_min"] = ("Donasi Minimum", "Donation Min"),
        ["rulesets.form.donation_max"] = ("Donasi Maksimum", "Donation Max"),
        ["rulesets.form.gold_buy"] = ("Beli Emas", "Gold Buy"),
        ["rulesets.form.gold_sell"] = ("Jual Emas", "Gold Sell"),
        ["rulesets.form.loan_enabled"] = ("Pinjaman Aktif", "Loan Enabled"),
        ["rulesets.form.insurance_enabled"] = ("Asuransi Aktif", "Insurance Enabled"),
        ["rulesets.form.saving_goal_enabled"] = ("Target Tabungan Aktif", "Saving Goal Enabled"),
        ["rulesets.form.description_placeholder"] = ("Contoh: Simulasi panjang dengan fokus misi dan kepatuhan aturan.", "Example: Long simulation focused on mission and rules compliance."),
        ["rulesets.form.description_hint"] = ("Deskripsi menjelaskan tujuan/karakter aturan. Nomor versi dibuat otomatis oleh sistem.", "Description should explain the rule intent/character. Version numbers are generated automatically."),
        ["rulesets.form.help.core_setup"] = ("Atur mode permainan, jumlah aksi, kas awal, urutan pemain, dan hasil kerja lepas.", "Set the game mode, actions per turn, starting cash, player ordering, and freelance reward."),
        ["rulesets.form.help.weekday_features"] = ("Tentukan apakah event khusus Jumat/Sabtu/Minggu berjalan di sesi ini.", "Decide whether Friday/Saturday/Sunday special events are enabled in this session."),
        ["rulesets.form.help.constraints"] = ("Batasan ini menjaga permainan tetap sesuai aturan stok bahan, kas, dan urutan kebutuhan.", "These constraints keep gameplay aligned with inventory, cash floor, and need-order rules."),
        ["rulesets.form.help.economy_advanced"] = ("Atur rentang donasi, izin transaksi emas, dan fitur khusus mode mahir.", "Set donation range, gold trade permissions, and advanced-mode features."),
        ["rulesets.config_read_guide"] = ("Gunakan ringkasan ini untuk cek apakah setup sesi, alur aksi harian, dan aturan ekonomi sudah sesuai yang Anda inginkan.", "Use this summary to verify that session setup, daily action flow, and economy rules match your intent."),
        ["rulesets.analytics.title"] = ("Analitika Set Aturan", "Ruleset Analytics"),
        ["rulesets.analytics.subtitle"] = ("Ringkasan Analitika per Set Aturan", "Analytics Summary per Ruleset"),
        ["rulesets.analytics.back"] = ("Kembali ke Analitika", "Back to Analytics"),
        ["rulesets.analytics.session_count"] = ("Jumlah sesi", "Session count"),
        ["rulesets.analytics.learning_aggregate"] = ("Agregat pembelajaran", "Learning aggregate"),
        ["rulesets.analytics.quest_aggregate"] = ("Agregat misi", "Quest aggregate"),
        ["rulesets.analytics.session"] = ("Sesi", "Session"),
        ["rulesets.analytics.events"] = ("Aktivitas", "Events"),
        ["rulesets.analytics.detail"] = ("Rincian", "Detail"),
        ["rulesets.analytics.empty_sessions"] = ("Belum ada sesi yang memakai Set Aturan ini.", "No sessions are using this ruleset yet."),
        ["rulesets.analytics.player_performance_empty"] = ("Belum ada performa pengguna yang bisa ditampilkan.", "No user performance available to display."),
        ["rulesets.analytics.user_learning"] = ("Performa Pembelajaran Pengguna", "User Learning Performance"),
        ["rulesets.analytics.user_quest"] = ("Performa Misi Pengguna", "User Quest Performance"),
        ["rulesets.error.load_list_failed"] = ("Gagal mengambil set aturan. Status: {status}", "Failed to fetch rulesets. Status: {status}"),
        ["rulesets.error.invalid_list_response"] = ("Respons daftar set aturan tidak valid.", "Invalid ruleset list response."),
        ["rulesets.error.name_required"] = ("Nama set aturan wajib diisi.", "Ruleset name is required."),
        ["rulesets.error.invalid_config_json"] = ("JSON konfigurasi tidak valid.", "Configuration JSON is invalid."),
        ["rulesets.error.create_failed"] = ("Gagal membuat set aturan. Status: {status}", "Failed to create ruleset. Status: {status}"),
        ["rulesets.error.load_for_edit_failed"] = ("Gagal memuat set aturan untuk diedit. Status: {status}", "Failed to load ruleset for editing. Status: {status}"),
        ["rulesets.error.load_clone_template_failed"] = ("Gagal memuat template duplikasi set aturan. Status: {status}", "Failed to load ruleset duplication template. Status: {status}"),
        ["rulesets.error.load_detail_failed"] = ("Gagal memuat rincian set aturan. Status: {status}", "Failed to load ruleset details. Status: {status}"),
        ["rulesets.error.invalid_detail_response"] = ("Respons rincian set aturan tidak valid.", "Invalid ruleset detail response."),
        ["rulesets.error.load_default_components_failed"] = ("Gagal mengambil komponen default. Status: {status}", "Failed to fetch default components. Status: {status}"),
        ["rulesets.error.invalid_default_components_response"] = ("Respons komponen default tidak valid.", "Invalid default components response."),
        ["rulesets.error.load_components_failed"] = ("Gagal mengambil katalog komponen ruleset. Status: {status}", "Failed to fetch ruleset component catalog. Status: {status}"),
        ["rulesets.error.invalid_components_response"] = ("Respons katalog komponen ruleset tidak valid.", "Invalid ruleset component catalog response."),
        ["rulesets.error.update_failed"] = ("Gagal memperbarui set aturan. Status: {status}", "Failed to update ruleset. Status: {status}"),
        ["rulesets.error.activate_version_failed"] = ("Gagal mengaktifkan versi set aturan", "Failed to activate ruleset version"),
        ["rulesets.error.delete_version_failed"] = ("Gagal menghapus versi set aturan", "Failed to delete ruleset version"),
        ["rulesets.error.delete_failed"] = ("Gagal menghapus set aturan", "Failed to delete ruleset"),
        ["rulesets.error.bulk_delete_empty"] = ("Belum ada set aturan yang dipilih.", "No rulesets were selected."),
        ["rulesets.bulk_delete_success"] = ("Berhasil menghapus {count} set aturan.", "Successfully deleted {count} rulesets."),
        ["rulesets.bulk_delete_partial"] = ("Sebagian berhasil dihapus. Sukses: {success}, gagal: {failed}.", "Partial deletion completed. Success: {success}, failed: {failed}."),
        ["rulesets.bulk_delete_failed"] = ("Semua penghapusan gagal. Total gagal: {failed}.", "All deletions failed. Total failed: {failed}."),
        ["rulesets.delete_confirm"] = ("Hapus set aturan ini?", "Delete this ruleset?"),

        ["common.name"] = ("Nama", "Name"),
        ["common.description"] = ("Deskripsi", "Description"),
        ["common.status"] = ("Status", "Status"),
        ["common.created"] = ("Dibuat", "Created"),
        ["common.mode"] = ("Mode", "Mode"),
        ["common.action"] = ("Aksi", "Action"),
        ["common.detail"] = ("Rincian", "Detail"),
        ["common.view"] = ("Lihat", "View"),
        ["common.cancel"] = ("Batal", "Cancel"),
        ["common.version"] = ("Versi", "Version"),
        ["common.latest_version"] = ("Versi Terbaru", "Latest Version"),
        ["common.player"] = ("Pemain", "Player"),
        ["common.player_id"] = ("ID Pemain", "Player ID"),
        ["common.rank"] = ("Peringkat", "Rank"),
        ["common.turn_order"] = ("Urutan Giliran", "Turn Order"),
        ["common.session_id"] = ("ID Sesi", "Session ID"),
        ["common.ruleset_id"] = ("ID Set Aturan", "Ruleset ID"),
        ["common.ruleset"] = ("Set Aturan", "Ruleset"),
        ["common.transaction_amount"] = ("Nominal", "Amount"),
        ["common.time"] = ("Waktu", "Time"),
        ["common.direction"] = ("Arah", "Direction"),
        ["common.category"] = ("Kategori", "Category"),
        ["common.path"] = ("Path", "Path"),
        ["common.value"] = ("Nilai", "Value"),
        ["common.computed"] = ("Dihitung", "Computed"),
        ["common.start"] = ("Mulai", "Start"),
        ["common.finish"] = ("Selesai", "Finish"),
        ["common.session"] = ("Sesi", "Session"),
        ["common.na"] = ("Tidak Ada", "N/A"),
        ["status.session.created"] = ("Dibuat", "Created"),
        ["status.session.started"] = ("Dimulai", "Started"),
        ["status.session.ended"] = ("Selesai", "Ended"),
        ["status.session.cancelled"] = ("Dibatalkan", "Cancelled"),
        ["status.session.unknown"] = ("Tidak Diketahui", "Unknown"),
        ["status.ruleset.active"] = ("Aktif", "Active"),
        ["status.ruleset.draft"] = ("Draf", "Draft"),
        ["status.ruleset.retired"] = ("Pensiun", "Retired"),
        ["status.ruleset.unknown"] = ("Tidak Diketahui", "Unknown"),

        ["error.title"] = ("Terjadi Kesalahan", "An Error Occurred"),
        ["error.notice"] = ("Pemberitahuan Sistem", "System Notice"),
        ["error.message"] = ("Terjadi kesalahan saat memproses permintaan.", "An error occurred while processing your request."),
        ["error.submessage"] = ("Silakan coba lagi, atau cek rincian permintaan bila masalah berlanjut.", "Please try again, or check request details if the issue persists."),
        ["error.request_id"] = ("ID Permintaan", "Request ID"),
        ["error.dev_mode"] = ("Mode Pengembangan", "Development Mode"),
        ["error.dev_desc"] = ("Mode Pengembangan menampilkan rincian kesalahan untuk debugging lokal.", "Development mode shows detailed errors for local debugging."),
        ["error.dev_warning"] = ("Jangan aktifkan Pengembangan di produksi karena bisa mengekspos informasi sensitif.", "Do not enable Development in production because it can expose sensitive information."),
        ["error.dev_hint"] = ("Untuk debugging lokal, set ASPNETCORE_ENVIRONMENT ke Pengembangan.", "For local debugging, set ASPNETCORE_ENVIRONMENT to Development."),

        ["metric.total_event"] = ("Total Aktivitas Tercatat", "Total Recorded Activities"),
        ["metric.cash_in"] = ("Total Kas Masuk", "Total Cash In"),
        ["metric.cash_out"] = ("Total Kas Keluar", "Total Cash Out"),
        ["metric.net_cashflow"] = ("Arus Kas Bersih", "Net Cashflow"),
        ["metric.violations"] = ("Jumlah Pelanggaran Aturan", "Rule Violations"),
        ["metric.donation"] = ("Total Donasi", "Total Donations"),
        ["metric.gold_qty"] = ("Jumlah Emas", "Gold Qty"),
        ["metric.happiness"] = ("Total Poin Kebahagiaan", "Total Happiness Points"),
        ["metric.need_points"] = ("Poin Kebutuhan", "Need Points"),
        ["metric.need_bonus"] = ("Bonus Kebutuhan", "Need Bonus"),
        ["metric.donation_points"] = ("Poin Donasi", "Donation Points"),
        ["metric.gold_points"] = ("Poin Emas", "Gold Points"),
        ["metric.pension_points"] = ("Poin Pensiun", "Pension Points"),
        ["metric.saving_goal"] = ("Poin Target Tabungan", "Saving Goal Points"),
        ["metric.loan_unpaid"] = ("Pinjaman Belum Lunas", "Loan Unpaid"),
        ["metric.mission_penalty"] = ("Penalti Misi", "Mission Penalty"),
        ["metric.loan_penalty"] = ("Penalti Pinjaman", "Loan Penalty"),
        ["metric.orders_completed"] = ("Pesanan Selesai", "Orders Completed"),
        ["metric.inventory_ingredient"] = ("Stok Bahan", "Ingredient Inventory"),
        ["metric.actions_used"] = ("Aksi Terpakai", "Actions Used"),
        ["metric.primary_need_compliance"] = ("Kepatuhan Kebutuhan Primer", "Primary Need Compliance"),

        ["gameplay.title"] = ("Cuplikan permainan & turunan", "Gameplay snapshot & derived"),
        ["gameplay.raw"] = ("Variabel Permainan Mentah", "Raw Gameplay Variables"),
        ["gameplay.derived"] = ("Metrik Turunan", "Derived Metrics"),

        ["state.no_sessions"] = ("Belum ada sesi tersedia.", "No sessions available yet."),
        ["state.no_players"] = ("Belum ada data pemain.", "No player data yet."),
        ["state.no_player_data"] = ("Belum ada data pemain.", "No player data yet."),
        ["state.no_rulesets"] = ("Belum ada set aturan.", "No rulesets yet."),
        ["state.no_versions"] = ("Belum ada versi.", "No versions yet."),
        ["state.true"] = ("Ya", "Yes"),
        ["state.false"] = ("Tidak", "No"),
        ["state.null"] = ("Kosong", "Null")
    };

    /// <summary>
    /// Menjalankan fungsi NormalizeLanguage sebagai bagian dari alur file ini.
    /// </summary>
    public static string NormalizeLanguage(string? language)
    {
        return string.Equals(language, AuthConstants.LanguageEn, StringComparison.OrdinalIgnoreCase)
            ? AuthConstants.LanguageEn
            : AuthConstants.LanguageId;
    }

    /// <summary>
    /// Menjalankan fungsi TranslateSessionStatus sebagai bagian dari alur file ini.
    /// </summary>
    public static string TranslateSessionStatus(HttpContext context, string? status)
    {
        var normalized = status?.Trim().ToUpperInvariant();
        return normalized switch
        {
            "CREATED" => Translate(context, "status.session.created"),
            "STARTED" => Translate(context, "status.session.started"),
            "ENDED" => Translate(context, "status.session.ended"),
            "CANCELLED" => Translate(context, "status.session.cancelled"),
            "CANCELED" => Translate(context, "status.session.cancelled"),
            _ => string.IsNullOrWhiteSpace(status) ? Translate(context, "status.session.unknown") : status!
        };
    }

    /// <summary>
    /// Menjalankan fungsi TranslateRulesetStatus sebagai bagian dari alur file ini.
    /// </summary>
    public static string TranslateRulesetStatus(HttpContext context, string? status)
    {
        var normalized = status?.Trim().ToUpperInvariant();
        return normalized switch
        {
            "ACTIVE" => Translate(context, "status.ruleset.active"),
            "DRAFT" => Translate(context, "status.ruleset.draft"),
            "RETIRED" => Translate(context, "status.ruleset.retired"),
            _ => string.IsNullOrWhiteSpace(status) ? Translate(context, "status.ruleset.unknown") : status!
        };
    }

    /// <summary>
    /// Menjalankan fungsi TranslateRulesetMode sebagai bagian dari alur file ini.
    /// </summary>
    public static string TranslateRulesetMode(HttpContext context, string? mode)
    {
        var normalized = mode?.Trim().ToUpperInvariant();
        return normalized switch
        {
            "PEMULA" => Translate(context, "rulesets.form.mode_beginner"),
            "BEGINNER" => Translate(context, "rulesets.form.mode_beginner"),
            "MAHIR" => Translate(context, "rulesets.form.mode_advanced"),
            "ADVANCED" => Translate(context, "rulesets.form.mode_advanced"),
            _ => string.IsNullOrWhiteSpace(mode) ? "-" : mode!
        };
    }

    /// <summary>
    /// Menjalankan fungsi Translate sebagai bagian dari alur file ini.
    /// </summary>
    public static string Translate(HttpContext context, string key)
    {
        var lang = NormalizeLanguage(context.Session.GetString(AuthConstants.SessionLanguageKey));
        if (!Lexicon.TryGetValue(key, out var term))
        {
            return key;
        }

        return lang == AuthConstants.LanguageEn ? term.En : term.Id;
    }
}

/// <summary>
/// Menyatakan peran utama tipe UiTextHttpContextExtensions pada modul ini.
/// </summary>
public static class UiTextHttpContextExtensions
{
    /// <summary>
    /// Menjalankan fungsi Translate sebagai bagian dari alur file ini.
    /// </summary>
    public static string T(this HttpContext context, string key) => UiText.Translate(context, key);
    /// <summary>
    /// Menjalankan fungsi TranslateSessionStatus sebagai bagian dari alur file ini.
    /// </summary>
    public static string TSessionStatus(this HttpContext context, string? status) => UiText.TranslateSessionStatus(context, status);
    /// <summary>
    /// Menjalankan fungsi TranslateRulesetStatus sebagai bagian dari alur file ini.
    /// </summary>
    public static string TRulesetStatus(this HttpContext context, string? status) => UiText.TranslateRulesetStatus(context, status);
    /// <summary>
    /// Menjalankan fungsi TranslateRulesetMode sebagai bagian dari alur file ini.
    /// </summary>
    public static string TRulesetMode(this HttpContext context, string? mode) => UiText.TranslateRulesetMode(context, mode);
}

