using Cashflowpoly.Ui.Models;

namespace Cashflowpoly.Ui.Infrastructure;

public static class UiText
{
    private static readonly Dictionary<string, (string Id, string En)> Lexicon = new(StringComparer.OrdinalIgnoreCase)
    {
        ["brand.chip"] = ("Lembar Petualang", "Adventurer's Ledger"),

        ["nav.home"] = ("Beranda", "Home"),
        ["nav.sessions"] = ("Sesi Permainan", "Game Sessions"),
        ["nav.players"] = ("Direktori Pemain", "Player Directory"),
        ["nav.analytics"] = ("Analitika", "Analytics"),
        ["nav.ruleset"] = ("Set Aturan", "Rulesets"),
        ["nav.privacy"] = ("Buku Aturan", "Rulebook"),

        ["auth.login"] = ("Masuk", "Sign In"),
        ["auth.logout"] = ("Keluar", "Logout"),
        ["auth.access"] = ("Akses Dasbor", "Dashboard Access"),
        ["auth.title"] = ("Masuk ke Cashflowpoly", "Sign In to Cashflowpoly"),
        ["auth.subtitle"] = ("Masuk dengan akun instruktur atau pemain untuk melanjutkan.", "Sign in with an instructor or player account to continue."),
        ["auth.display_name"] = ("Nama Tampilan", "Display Name"),
        ["auth.username"] = ("Nama Pengguna", "Username"),
        ["auth.password"] = ("Kata Sandi", "Password"),
        ["auth.submit"] = ("Masuk", "Sign In"),
        ["auth.no_account"] = ("Belum punya akun?", "Don't have an account?"),
        ["auth.have_account"] = ("Sudah punya akun?", "Already have an account?"),
        ["auth.register"] = ("Daftar", "Register"),
        ["auth.register_title"] = ("Buat Akun Baru", "Register New Account"),
        ["auth.register_subtitle"] = ("Buat akun baru agar bisa login ke game melalui API.", "Create a new account to sign in to the game through the API."),
        ["auth.confirm_password"] = ("Konfirmasi Kata Sandi", "Confirm Password"),
        ["auth.role"] = ("Peran Pengguna", "User Role"),
        ["auth.role_player"] = ("Pemain", "Player"),
        ["auth.role_instructor"] = ("Instruktur", "Instructor"),
        ["auth.submit_register"] = ("Buat Akun", "Create Account"),
        ["auth.login_panel_title"] = ("Sudah Punya Akun?", "Already Have an Account?"),
        ["auth.login_panel_desc"] = ("Masuk dengan akun Anda untuk melanjutkan pekerjaan.", "Sign in with your account to continue your work."),
        ["auth.login_panel_cta"] = ("MASUK", "SIGN IN"),
        ["auth.register_panel_title"] = ("Belum Punya Akun?", "Don't Have an Account Yet?"),
        ["auth.register_panel_desc"] = ("Buat akun baru untuk mulai mengelola sesi dan analitika.", "Create a new account to start managing sessions and analytics."),
        ["auth.register_panel_cta"] = ("DAFTAR", "REGISTER"),
        ["auth.placeholder.full_name"] = ("Nama Lengkap", "Full Name"),
        ["auth.placeholder.new_username"] = ("pemain_baru", "new_player"),
        ["auth.login_note.quick_access"] = ("Akses sesi lebih cepat", "Faster session access"),
        ["auth.login_note.realtime_monitoring"] = ("Pemantauan analitika waktu nyata", "Real-time analytics monitoring"),
        ["auth.login_note.centralized_ruleset"] = ("Manajemen Set Aturan terpusat", "Centralized ruleset management"),
        ["auth.error.login_required"] = ("Nama Pengguna dan Kata Sandi wajib diisi.", "Username and password are required."),
        ["auth.error.login_failed"] = ("Login gagal.", "Login failed."),
        ["auth.error.login_response_invalid"] = ("Respons login tidak valid.", "Invalid login response."),
        ["auth.error.register_required"] = ("Nama tampilan, Nama Pengguna, Kata Sandi, dan konfirmasi Kata Sandi wajib diisi.", "Display name, username, password, and confirmation are required."),
        ["auth.error.role_invalid"] = ("Peran tidak valid.", "Invalid role."),
        ["auth.error.confirm_mismatch"] = ("Konfirmasi Kata Sandi tidak sama.", "Password confirmation does not match."),
        ["auth.error.register_failed"] = ("Registrasi gagal.", "Registration failed."),
        ["auth.error.register_response_invalid"] = ("Respons registrasi tidak valid.", "Invalid registration response."),

        ["lang.toggle"] = ("EN", "ID"),
        ["lang.label"] = ("Bahasa", "Language"),
        ["lang.option.id"] = ("Bahasa Indonesia (ID)", "Indonesian (ID)"),
        ["lang.option.en"] = ("Bahasa Inggris (EN)", "English (EN)"),

        ["profile.settings"] = ("Pengaturan Web", "Web Settings"),
        ["profile.role"] = ("Peran", "Role"),
        ["layout.skip_to_content"] = ("Lewati ke konten", "Skip to content"),
        ["layout.toggle_nav"] = ("Buka/tutup menu navigasi", "Toggle navigation menu"),
        ["layout.logo_alt"] = ("Logo Cashflowpoly", "Cashflowpoly logo"),
        ["layout.profile_alt"] = ("Profil", "Profile"),
        ["footer.rulebook_copyright"] = ("Hak Cipta Buku Aturan", "Rulebook Copyright"),

        ["home.badge"] = ("Cashflowpoly", "Cashflowpoly"),
        ["home.title"] = ("Dashboard Analitika dan Set Aturan.", "Analytics and Ruleset Dashboard."),
        ["home.subtitle"] = ("Pantau sesi, performa pemain, dan aturan aktif dalam satu tempat.", "Monitor sessions, player performance, and active rules in one place."),
        ["home.player_badge"] = ("Dasbor Pemain", "Player Dashboard"),
        ["home.player_title"] = ("Pantau progres permainan Anda secara Waktu Nyata.", "Track your game progress in real time."),
        ["home.player_subtitle"] = ("Lihat status sesi, Set Aturan yang dapat Anda akses, dan ringkasan performa pribadi tanpa perlu membuka menu instruktur.", "View session status, accessible rulesets, and your personal performance summary without opening the instructor menu."),
        ["home.cta.sessions"] = ("Buka Sesi", "Open Sessions"),
        ["home.cta.analytics"] = ("Buka Analitika", "Open Analytics"),
        ["home.cta.my_progress"] = ("Lihat progres saya", "View my progress"),
        ["home.cta.open_ruleset"] = ("Buka Set Aturan", "Open rulesets"),
        ["home.feature.1"] = ("Validasi Buku Aturan dan skor otomatis.", "Automatic rulebook validation and scoring."),
        ["home.feature.2"] = ("Aktivasi Set Aturan per sesi dengan cepat.", "Quick per-session ruleset activation."),
        ["home.feature.3"] = ("Cuplikan arus kas dan pelanggaran.", "Cashflow and violation snapshots."),
        ["home.feature.4"] = ("Ringkasan pemain siap untuk evaluasi.", "Player summaries ready for evaluation."),
        ["home.player.feature.1"] = ("Pilih sesi dari menu Analitika tanpa Masukan UUID manual.", "Pick a session from Analytics without manual UUID input."),
        ["home.player.feature.2"] = ("Lihat metrik Arus Kas dan poin Anda dalam satu Dasbor.", "See your cashflow and points in one dashboard."),
        ["home.player.feature.3"] = ("Cek Set Aturan aktif untuk memahami target skor dan penalti.", "Check active rulesets to understand score targets and penalties."),
        ["home.player.feature.4"] = ("Pantau pembaruan data otomatis setiap 30 detik.", "Monitor automatic data updates every 30 seconds."),
        ["home.total_sessions"] = ("Total Sesi", "Total Sessions"),
        ["home.my_sessions"] = ("Sesi saya", "My sessions"),
        ["home.peers_in_session"] = ("Teman satu sesi", "Session peers"),
        ["home.available_rulesets"] = ("Set Aturan tersedia", "Available rulesets"),
        ["home.active_sessions"] = ("Sesi Aktif", "Active Sessions"),
        ["home.realtime"] = ("Waktu Nyata", "Real-time"),
        ["home.live"] = ("LANGSUNG", "LIVE"),
        ["home.server_time"] = ("Waktu server lokal", "Local server time"),
        ["home.sync_label"] = ("Sinkron data", "Data sync"),
        ["home.auto_refresh_note"] = ("Data diperbarui otomatis setiap 30 detik.", "Data refreshes automatically every 30 seconds."),
        ["home.error.realtime_status"] = ("Gagal sinkron waktu nyata ({status}).", "Realtime sync failed ({status})."),
        ["home.error.realtime_network"] = ("Gagal sinkron waktu nyata (kesalahan jaringan).", "Realtime sync failed (network error)."),
        ["home.ruleset_active"] = ("Set Aturan Aktif", "Active Ruleset"),
        ["home.players_monitored"] = ("Pemain Dipantau", "Players Monitored"),
        ["home.snapshot_demo"] = ("Cuplikan singkat untuk demo tampilan.", "Quick snapshot for UI demo."),
        ["home.guide.menu"] = ("Panduan Menu", "Menu Guide"),
        ["home.guide.title"] = ("Kumpulan cara penggunaan", "Usage playbook"),
        ["home.guide.subtitle"] = ("Gunakan panduan cepat ini supaya alur kerja dari Persiapan sampai analitik lebih rapi.", "Use this quick guide to keep the workflow from setup to analytics organized."),
        ["home.guide.sessions.title"] = ("Sesi", "Sessions"),
        ["home.guide.sessions.desc"] = ("Buka daftar sesi, pilih sesi aktif, lalu masuk Rincian pemain untuk analitik per individu.", "Open the session list, pick an active session, then open player details for per-player analytics."),
        ["home.guide.sessions.link"] = ("Buka menu Sesi", "Open Sessions"),
        ["home.guide.ruleset.title"] = ("Set Aturan", "Rulesets"),
        ["home.guide.ruleset.desc"] = ("Buat Set Aturan baru, cek versi, aktifkan versi yang tepat sebelum sesi dimulai.", "Create a new ruleset, review versions, and activate the right one before a session starts."),
        ["home.guide.ruleset.link"] = ("Buka menu Set Aturan", "Open Rulesets"),
        ["home.guide.analytics.title"] = ("Analitika", "Analytics"),
        ["home.guide.analytics.desc"] = ("Masukkan ID Sesi untuk melihat ringkasan Arus Kas, metrik misi, dan performa pemain.", "Enter a Session ID to view cashflow summary, mission metrics, and player performance."),
        ["home.guide.analytics.link"] = ("Buka menu Analitika", "Open Analytics"),
        ["home.guide.players.title"] = ("Pemain", "Players"),
        ["home.guide.players.desc"] = ("Lihat direktori pemain untuk validasi identitas sebelum meninjau Rincian metrik.", "Review the player directory to validate identities before inspecting metric details."),
        ["home.guide.players.link"] = ("Buka menu Pemain", "Open Players"),
        ["home.quick_flow.title"] = ("Alur Penggunaan Cepat", "Quick Workflow"),
        ["home.quick_flow.step1"] = ("Persiapan Set Aturan yang dibutuhkan di menu Set Aturan.", "Set up required rulesets in the Rulesets menu."),
        ["home.quick_flow.step2"] = ("Masuk menu Sesi, pilih sesi, lalu aktifkan Set Aturan.", "Go to Sessions, choose a session, then activate a ruleset."),
        ["home.quick_flow.step3"] = ("Impor aktivitas permainan dari IDN/simulator ke API.", "Ingest gameplay events from IDN/simulator into the API."),
        ["home.quick_flow.step4"] = ("Cek Analitika untuk ringkasan sesi dan tren metrik.", "Check Analytics for session summaries and metric trends."),
        ["home.quick_flow.step5"] = ("Buka Rincian pemain untuk evaluasi performa per individu.", "Open player details for per-player performance evaluation."),
        ["home.player_guide.menu"] = ("Panduan Pemain", "Player Guide"),
        ["home.player_guide.title"] = ("Langkah cepat melihat progres", "Quick steps to view progress"),
        ["home.player_guide.subtitle"] = ("Tampilan pemain difokuskan untuk membaca hasil permainan Anda dengan cepat.", "The player view is focused on reading your own game results quickly."),
        ["home.player_guide.analytics.title"] = ("Analitika Saya", "My Analytics"),
        ["home.player_guide.analytics.desc"] = ("Pilih sesi dari daftar pilihan, lalu cek arus kas, poin, dan risiko pribadi di satu halaman.", "Select a session from the dropdown, then check cashflow, points, and personal risk on one page."),
        ["home.player_guide.analytics.link"] = ("Buka Analitika Saya", "Open My Analytics"),
        ["home.player_guide.ruleset.title"] = ("Set Aturan Aktif", "Active Rulesets"),
        ["home.player_guide.ruleset.desc"] = ("Lihat daftar Set Aturan untuk memahami target poin, penalti, dan batasan aksi permainan.", "View the ruleset list to understand point targets, penalties, and gameplay action limits."),
        ["home.player_guide.ruleset.link"] = ("Buka Set Aturan", "Open Rulesets"),
        ["home.player_guide.rulebook.title"] = ("Buku Aturan", "Rulebook"),
        ["home.player_guide.rulebook.desc"] = ("Buka Buku Aturan kapan saja saat butuh klarifikasi aturan permainan.", "Open the rulebook anytime when you need rule clarifications."),
        ["home.player_guide.rulebook.link"] = ("Buka Buku Aturan", "Open Rulebook"),
        ["home.player_flow.title"] = ("Alur Pemain yang Disarankan", "Recommended Player Flow"),
        ["home.player_flow.step1"] = ("Masuk ke Analitika lalu pilih sesi yang sedang Anda ikuti.", "Open Analytics then choose the session you are in."),
        ["home.player_flow.step2"] = ("Pantau Bersih Arus Kas dan poin kebutuhan untuk evaluasi keputusan harian.", "Monitor net cashflow and need points to evaluate daily decisions."),
        ["home.player_flow.step3"] = ("Periksa penalti misi dan status pinjaman untuk menghindari skor turun.", "Check mission penalties and loan status to avoid score drops."),
        ["home.player_flow.step4"] = ("Cocokkan progres Anda dengan Set Aturan agar strategi berikutnya lebih tepat.", "Match your progress with the ruleset so your next strategy is more accurate."),

        ["privacy.title"] = ("Buku Aturan Cashflowpoly", "Cashflowpoly Rulebook"),
        ["privacy.subtitle"] = ("", ""),
        ["privacy.outline_title"] = ("Daftar Isi Aturan", "Rulebook Contents"),
        ["privacy.total_sections"] = ("Jumlah Bagian Aturan", "Total Rulebook Sections"),
        ["privacy.total_points"] = ("Jumlah Aturan Skoring", "Total Scoring Rules"),
        ["privacy.back_to_top"] = ("Kembali ke atas", "Back to top"),
        ["privacy.empty_sections"] = ("Bagian Buku Aturan belum tersedia.", "Rulebook sections are not available yet."),
        ["privacy.empty_scoring"] = ("Ringkasan poin belum tersedia.", "Scoring summary is not available yet."),
        ["privacy.happiness_summary"] = ("Ringkasan Poin Kebahagiaan", "Happiness Points Summary"),
        ["privacy.copyright_title"] = ("Hak Cipta Buku Aturan", "Rulebook Copyright"),
        ["privacy.copyright_desc"] = ("Materi Buku Aturan Cashflowpoly digunakan untuk keperluan pembelajaran internal. Dilarang menyalin, menggandakan, atau mendistribusikan ulang tanpa izin tertulis dari pemilik hak cipta.", "Cashflowpoly rulebook materials are for internal learning purposes. Copying, reproducing, or redistributing without written permission from the copyright owner is prohibited."),
        ["privacy.category"] = ("Kategori", "Category"),
        ["privacy.rule"] = ("Aturan", "Rule"),

        ["analytics.dashboard"] = ("Pusat Analitika", "Analytics Center"),
        ["analytics.title"] = ("Analitika Sesi", "Session Analytics"),
        ["analytics.subtitle"] = ("Pilih sesi untuk melihat ringkasan performa, arus kas, dan aturan aktif.", "Select a session to view performance summary, cashflow, and active ruleset."),
        ["analytics.button"] = ("Tampilkan Analitika Sesi", "Show Session Analytics"),
        ["analytics.player_dashboard"] = ("Dasbor Progres Pemain", "Player Progress Dashboard"),
        ["analytics.player_title"] = ("Analitika Sesi Saya", "My Session Analytics"),
        ["analytics.player_subtitle"] = ("Pilih sesi yang Anda ikuti untuk melihat ringkasan performa dan metrik pribadi Anda.", "Select a session you joined to view your performance summary and personal metrics."),
        ["analytics.player_no_sessions"] = ("Belum ada sesi untuk akun pemain ini", "No sessions available for this player account"),
        ["analytics.player_button"] = ("Tampilkan Progres Saya", "Show My Progress"),
        ["analytics.workbench_title"] = ("Analitika Sesi", "Session Analytics"),
        ["analytics.workbench_subtitle"] = ("Pilih satu sesi, lalu semua ringkasan tampil otomatis.", "Pick one session, then all summaries appear automatically."),
        ["analytics.section.session_title"] = ("Pilih Sesi Analisis", "Select Session for Analysis"),
        ["analytics.section.session_desc"] = ("Tampilan ini juga memuat ringkasan Set Aturan aktif dari sesi yang dipilih.", "This view also includes the active ruleset summary from the selected session."),
        ["analytics.section.minimum_matrix_title"] = ("Matriks Metrik Minimum", "Minimum Metrics Matrix"),
        ["analytics.section.minimum_matrix_desc"] = ("Tabel audit metrik minimum per pemain sesuai definisi cuplikan analitika.", "Audit table of minimum per-player metrics based on analytics snapshot definitions."),
        ["analytics.section.ruleset_title"] = ("Ringkasan Set Aturan Aktif Sesi", "Session Active Ruleset Summary"),
        ["analytics.tips.instructor"] = ("Tips penggunaan menu Analitika", "Analytics menu tips"),
        ["analytics.tips.player"] = ("Tips membaca analitika pemain", "Player analytics tips"),
        ["analytics.tip_key.input"] = ("Masukan", "Input"),
        ["analytics.tip_key.interpretation"] = ("Interpretasi", "Interpretation"),
        ["analytics.tip_key.followup"] = ("Tindak lanjut", "Follow-up"),
        ["analytics.tip_key.select_session"] = ("Pilih Sesi", "Select Session"),
        ["analytics.tip_key.focus_score"] = ("Fokus Skor", "Score Focus"),
        ["analytics.tip_key.risk_control"] = ("Kontrol Risiko", "Risk Control"),
        ["analytics.tip.input"] = ("Masukkan ID Sesi yang valid.", "Enter a valid Session ID."),
        ["analytics.tip.interpretation"] = ("Baca ringkasan sesi dulu sebelum melihat grafik per pemain.", "Read the session summary first before reviewing per-player charts."),
        ["analytics.tip.followup"] = ("Buka Rincian sesi/pemain untuk investigasi metrik spesifik.", "Open session/player details to investigate specific metrics."),
        ["analytics.tip.select_session"] = ("Gunakan daftar pilihan sesi, tidak perlu masukan UUID manual.", "Use the session dropdown, no manual UUID input needed."),
        ["analytics.tip.focus_score"] = ("Pantau arus kas bersih, poin kebutuhan, dan poin target tabungan.", "Track net cashflow, need points, and saving goal points."),
        ["analytics.tip.risk_control"] = ("Perhatikan penalti misi, penalti pinjaman, dan status pinjaman belum lunas.", "Watch mission penalties, loan penalties, and unpaid loan status."),
        ["analytics.players"] = ("Pemain", "Players"),
        ["analytics.chart.session_summary"] = ("Ringkasan Kinerja Sesi", "Session Performance Summary"),
        ["analytics.chart.cashflow_per_player"] = ("Arus Kas per Pemain", "Cashflow per Player"),
        ["analytics.chart.personal_cashflow"] = ("Arus Kas Pribadi", "Personal Cashflow"),
        ["analytics.chart.game_points"] = ("Poin Permainan", "Game Points"),
        ["analytics.chart.risk_control"] = ("Kontrol Risiko", "Risk Control"),
        ["analytics.chart.operations"] = ("Operasional dan Kepatuhan", "Operations and Compliance"),
        ["analytics.chart.cash_in"] = ("Kas Masuk", "Cash In"),
        ["analytics.chart.cash_out"] = ("Kas Keluar", "Cash Out"),
        ["analytics.chart.net"] = ("Bersih", "Net"),
        ["analytics.chart.value"] = ("Nilai", "Value"),
        ["analytics.chart.points"] = ("Poin", "Points"),
        ["analytics.chart.risk"] = ("Risiko", "Risk"),
        ["analytics.chart.summary"] = ("Ringkasan", "Summary"),
        ["analytics.chart.event"] = ("Aktivitas", "Event"),
        ["analytics.chart.unavailable"] = ("Grafik belum tersedia.", "Chart is not available yet."),
        ["analytics.chart.no_data"] = ("Belum ada data untuk ditampilkan.", "No data available to display."),

        ["sessions.management"] = ("Manajemen Sesi", "Session Management"),
        ["sessions.title"] = ("Daftar Sesi Permainan", "Game Session List"),
        ["sessions.subtitle"] = ("Pantau status sesi dan buka rincian analitika tiap sesi.", "Monitor session status and open analytics details for each session."),
        ["sessions.player_management"] = ("Sesi Pemain", "Player Sessions"),
        ["sessions.player_title"] = ("Daftar sesi saya", "My session list"),
        ["sessions.player_subtitle"] = ("Lihat sesi yang Anda ikuti dan buka Rincian progres permainan Anda.", "View sessions you joined and open your gameplay progress details."),
        ["sessions.readonly"] = ("Hanya Baca", "Read-only"),
        ["sessions.total_sessions"] = ("Total Sesi", "Total Sessions"),
        ["sessions.my_sessions"] = ("Sesi saya", "My sessions"),
        ["sessions.started"] = ("Sedang Berjalan", "In Progress"),
        ["sessions.ended"] = ("Sesi Selesai", "Completed Sessions"),
        ["sessions.tips.instructor.title"] = ("Tips penggunaan menu Sesi", "Sessions menu tips"),
        ["sessions.tips.player.title"] = ("Tips membaca sesi untuk pemain", "Player session tips"),
        ["sessions.step"] = ("Langkah", "Step"),
        ["sessions.tips.instructor.step1"] = ("Pilih sesi pada kolom Rincian.", "Choose a session from the detail column."),
        ["sessions.tips.instructor.step2"] = ("Aktifkan Set Aturan pada halaman Rincian sesi (instruktur).", "Activate a ruleset on the session detail page (instructor)."),
        ["sessions.tips.instructor.step3"] = ("Masuk ke Rincian pemain untuk evaluasi metrik individual.", "Open player details to evaluate individual metrics."),
        ["sessions.tips.player.step1"] = ("Pilih sesi yang ingin ditinjau.", "Choose the session you want to review."),
        ["sessions.tips.player.step2"] = ("Buka Rincian sesi untuk melihat ringkasan performa pribadi Anda.", "Open session details to view your personal performance summary."),
        ["sessions.tips.player.step3"] = ("Cek linimasa aktivitas agar keputusan per giliran lebih mudah dievaluasi.", "Check the event timeline so per-turn decisions are easier to evaluate."),
        ["sessions.view_progress"] = ("Lihat Rincian Sesi", "View Session Details"),
        ["sessions.live_log"] = ("Log Sesi Real-time", "Real-time Session Log"),
        ["sessions.detail_title"] = ("Rincian dan Analitika Sesi", "Session Details and Analytics"),
        ["sessions.analytics_title"] = ("Analitika Sesi", "Session Analytics"),
        ["sessions.activate_ruleset"] = ("Ganti/Atur Set Aturan Aktif", "Set or Change Active Ruleset"),
        ["sessions.winner.title"] = ("Pemenang Sesi", "Session Winner"),
        ["sessions.winner.subtitle"] = ("Performa terbaik pada sesi ini", "Best performance in this session"),
        ["sessions.winner.net"] = ("Bersih Arus Kas", "Net cashflow"),
        ["sessions.winner.happiness"] = ("Kebahagiaan", "Happiness"),
        ["sessions.winner.cash_in"] = ("Kas Masuk", "Cash in"),
        ["sessions.champion.title"] = ("Juara Kategori Sesi", "Session Category Champions"),
        ["sessions.champion.subtitle"] = ("Dipisahkan menjadi juara peduli donasi dan juara dana pensiun.", "Separated into donation care and pension fund champions."),
        ["sessions.champion.donation"] = ("Juara Peduli Donasi", "Donation Care Champion"),
        ["sessions.champion.pension"] = ("Juara Dana Pensiun", "Pension Fund Champion"),
        ["sessions.champion.none"] = ("Belum ada data juara kategori untuk sesi ini.", "No category champion data for this session yet."),
        ["sessions.rank_label"] = ("Juara", "Champion"),
        ["sessions.active_ruleset.title"] = ("Set Aturan Aktif Sesi", "Session Active Ruleset"),
        ["sessions.active_ruleset.subtitle"] = ("Set Aturan ini menjadi acuan validasi aturan dan penilaian pada sesi ini.", "This ruleset is the source of rule validation and scoring in this session."),
        ["sessions.active_ruleset.empty"] = ("Belum ada Set Aturan aktif pada sesi ini.", "No active ruleset for this session yet."),
        ["sessions.ruleset_title"] = ("Pilih Set Aturan untuk Sesi Ini", "Select Ruleset for This Session"),
        ["sessions.ruleset_hint"] = ("Masukkan versi aturan (contoh: 1 atau versi terbaru).", "Enter ruleset version (for example: 1 or latest)."),
        ["sessions.activate"] = ("Aktifkan Aturan", "Activate Ruleset"),
        ["sessions.ruleset_guide"] = ("Panduan Aktivasi Set Aturan", "Ruleset Activation Guide"),
        ["sessions.ruleset_step1"] = ("Pilih set aturan yang akan dipakai.", "Choose the ruleset to use."),
        ["sessions.ruleset_step2"] = ("Pilih versi aturan yang ingin diaktifkan.", "Choose the ruleset version to activate."),
        ["sessions.note"] = ("Catatan", "Note"),
        ["sessions.ruleset_note"] = ("Pastikan versi berstatus AKTIF sebelum menyimpan.", "Ensure the version is ACTIVE before saving."),
        ["sessions.timeline"] = ("Linimasa", "Timeline"),
        ["sessions.timeline_title"] = ("Linimasa Aktivitas Sesi", "Session Activity Timeline"),
        ["sessions.timeline_subtitle"] = ("Urutan aktivitas berdasarkan waktu dan nomor urut aktivitas.", "Activity order based on timestamp and event sequence."),
        ["sessions.timeline_chart_progress"] = ("Diagram Aktivitas dari Awal hingga Selesai", "Event Timeline from Start to Finish"),
        ["sessions.timeline_chart_actor"] = ("Sebaran Aktivitas per Aktor terhadap Waktu", "Event Distribution by Actor Over Time"),
        ["sessions.timeline_seq"] = ("Urut", "Seq"),
        ["sessions.timeline_day_turn"] = ("Hari dan Giliran Terakhir", "Latest Day and Turn"),
        ["sessions.day_label"] = ("Hari", "Day"),
        ["sessions.turn_label"] = ("Giliran", "Turn"),
        ["sessions.activity_default"] = ("Detail aktivitas belum tersedia", "Activity details not available"),
        ["sessions.timeline_actor"] = ("Aktor Aktivitas Terakhir", "Latest Activity Actor"),
        ["sessions.timeline_flow"] = ("Alur", "Flow"),
        ["sessions.timeline_description"] = ("Penjelasan", "Description"),
        ["sessions.timeline_empty"] = ("Belum ada aktivitas linimasa pada sesi ini.", "No timeline events for this session yet."),
        ["sessions.timeline_chart_cumulative_events"] = ("Kumulatif Aktivitas", "Cumulative Events"),
        ["sessions.timeline_chart_event_sequence"] = ("Urutan aktivitas", "Event sequence order"),
        ["sessions.timeline_chart_minutes_since_first"] = ("Menit sejak aktivitas pertama", "Minutes since first event"),
        ["sessions.timeline_chart_event_count"] = ("Jumlah aktivitas (kumulatif)", "Event count (cumulative)"),
        ["sessions.timeline_chart_events_per_turn"] = ("Jumlah aktivitas per giliran", "Event count per turn"),
        ["sessions.timeline_chart_turn_number"] = ("Nomor giliran", "Turn number"),
        ["sessions.timeline_tooltip_minutes"] = ("+{value} menit", "+{value} min"),
        ["sessions.timeline_tooltip_event"] = ("Aktivitas #{event} | urut {seq} | {actor} | {action}", "Event #{event} | seq {seq} | {actor} | {action}"),
        ["sessions.timeline_tooltip_actor"] = ("{actor} | hari {day} ({weekday}) | giliran {turn} | urut {seq} | {action}", "{actor} | day {day} ({weekday}) | turn {turn} | seq {seq} | {action}"),
        ["sessions.timeline_actor_help"] = ("Kategori aktor di grafik: siapa yang memicu aktivitas selama sesi.", "Actor categories in the chart: who triggered events during the session."),
        ["sessions.journey.board_title"] = ("Jejak perjalanan permainan", "Board-style game journey"),
        ["sessions.journey.board_subtitle"] = ("Visual papan ini otomatis mengikuti urutan aktivitas terbaru yang masuk dari IDN/API.", "This board visual automatically follows the latest event order from IDN/API."),
        ["sessions.journey.last_sync"] = ("Sinkron Data Terakhir", "Last Data Sync"),
        ["sessions.journey.latest_activity"] = ("Aksi Terakhir", "Latest Action"),
        ["sessions.journey.graph_title"] = ("Grafik Interaktif Pergerakan IDN", "Interactive IDN Movement Graph"),
        ["sessions.journey.graph_subtitle"] = ("Klik titik grafik untuk menyorot pergerakan pemain pada papan jejak dan daftar aktivitas.", "Click chart points to highlight player movements on the journey board and activity feed."),
        ["sessions.journey.graph_unavailable"] = ("Grafik interaktif belum tersedia.", "Interactive graph is not available yet."),
        ["sessions.journey.graph_empty"] = ("Belum ada pergerakan untuk divisualkan pada grafik.", "No movements are available to visualize on the chart."),
        ["sessions.journey.graph_axis_seq"] = ("Urutan Aktivitas", "Event Sequence"),
        ["sessions.journey.graph_axis_order"] = ("Urutan Pergerakan", "Movement Order"),
        ["sessions.journey.no_events"] = ("Belum ada aktivitas untuk divisualkan.", "No events available to visualize yet."),
        ["sessions.journey.realtime_status"] = ("Gagal sinkron alur permainan (status {status}).", "Failed to sync gameplay journey (status {status})."),
        ["sessions.journey.realtime_network"] = ("Koneksi ke server terputus saat sinkron alur permainan.", "Connection to server was lost while syncing gameplay journey."),
        ["sessions.actor.player"] = ("Pemain", "Player"),
        ["sessions.actor.system"] = ("Sistem", "System"),
        ["sessions.actor.instructor"] = ("Instruktur", "Instructor"),
        ["sessions.actor.other"] = ("Lainnya", "Other"),
        ["sessions.actor.player.desc"] = ("Aksi yang dilakukan pemain selama permainan.", "Actions performed by players during gameplay."),
        ["sessions.actor.system.desc"] = ("Aktivitas otomatis dari sistem/mesin aturan.", "Automatic events generated by the system/rules engine."),
        ["sessions.actor.instructor.desc"] = ("Aktivitas yang dipicu instruktur (kontrol sesi).", "Events triggered by instructors (session controls)."),
        ["sessions.actor.other.desc"] = ("Aktivitas dengan tipe aktor di luar tiga kategori utama.", "Events with actor types outside the three primary categories."),

        ["players.management"] = ("Manajemen Pemain", "Player Management"),
        ["players.title"] = ("Direktori Pemain", "Player Directory"),
        ["players.subtitle"] = ("Daftar pemain untuk validasi identitas dan akses rincian performa.", "Player list for identity validation and access to performance details."),
        ["players.total_players"] = ("Total Pemain", "Total Players"),
        ["players.total_sessions"] = ("Total Sesi Diikuti", "Total Sessions Joined"),
        ["players.tips.title"] = ("Tips penggunaan menu Pemain", "Players menu tips"),
        ["players.tip_key.validate"] = ("Validasi", "Validation"),
        ["players.tip_key.tracking"] = ("Pelacakan", "Tracking"),
        ["players.tip_key.analysis"] = ("Analisis", "Analysis"),
        ["players.tip.validate"] = ("Pastikan nama pemain sesuai data sesi.", "Make sure player names match session data."),
        ["players.tip.tracking"] = ("Gunakan ID Pemain untuk pelacakan aktivitas/transaksi.", "Use Player ID to trace events/transactions."),
        ["players.tip.analysis"] = ("Masuk Rincian sesi untuk membuka metrik pemain per sesi.", "Open session details to view per-session player metrics."),
        ["players.count_suffix"] = ("pemain", "players"),
        ["players.winner_badge"] = ("Juara 1", "Winner 1"),
        ["players.champion.donation_short"] = ("Donasi", "Donation"),
        ["players.champion.pension_short"] = ("Pensiun", "Pension"),
        ["players.add"] = ("Tambah", "Add"),
        ["players.name_placeholder"] = ("Nama pemain", "Player name"),
        ["players.detail_title"] = ("Rincian Pemain pada Sesi", "Player Session Details"),
        ["players.analytics_title"] = ("Analitika Pemain", "Player Analytics"),
        ["players.no_transactions"] = ("Belum ada transaksi.", "No transactions yet."),
        ["players.economy_snapshot"] = ("Ringkasan Ekonomi", "Economy Snapshot"),
        ["players.mission_risk"] = ("Misi dan Risiko", "Mission and Risk"),
        ["players.transaction_history"] = ("Riwayat Aktivitas Keuangan", "Financial Activity History"),
        ["players.gameplay_metrics"] = ("Metrik Permainan", "Gameplay Metrics"),
        ["players.financial_performance"] = ("Performa Finansial", "Financial Performance"),
        ["players.strategy_execution"] = ("Strategi & Eksekusi", "Strategy & Execution"),
        ["players.behavior_signals"] = ("Sinyal Perilaku", "Behavior Signals"),
        ["players.metric.net_worth_index"] = ("Indeks Kekayaan Bersih", "Net Worth Index"),
        ["players.metric.income_diversification"] = ("Diversifikasi Pendapatan", "Income Diversification"),
        ["players.metric.expense_efficiency"] = ("Efisiensi Pengeluaran", "Expense Efficiency"),
        ["players.metric.business_profit_margin"] = ("Margin Laba Bisnis", "Business Profit Margin"),
        ["players.metric.growth_pattern_ratio"] = ("Rasio Pola Pertumbuhan", "Growth Pattern Ratio"),
        ["players.metric.risk_appetite"] = ("Selera Risiko (0-100)", "Risk Appetite (0-100)"),
        ["players.metric.debt_leverage"] = ("Leverage Utang", "Debt Leverage"),
        ["players.metric.goal_setting_ambition"] = ("Ambisi Penetapan Target", "Goal Setting Ambition"),
        ["players.metric.meal_order_success"] = ("Keberhasilan Pesanan Makanan", "Meal Order Success"),
        ["players.metric.action_efficiency"] = ("Efisiensi Aksi", "Action Efficiency"),
        ["players.metric.planning_horizon"] = ("Cakrawala Perencanaan", "Planning Horizon"),
        ["players.metric.donation_aggressiveness"] = ("Agresivitas Donasi", "Donation Aggressiveness"),
        ["players.metric.donation_stability"] = ("Stabilitas Donasi (StdDev)", "Donation Stability (StdDev)"),
        ["players.metric.business_efficiency_ratio"] = ("Rasio Efisiensi Bisnis", "Business Efficiency Ratio"),
        ["players.metric.gold_roi"] = ("ROI Emas", "Gold ROI"),
        ["players.metric.mission_achievement"] = ("Pencapaian Misi", "Mission Achievement"),
        ["players.metric.fulfillment_diversity"] = ("Keberagaman Pemenuhan", "Fulfillment Diversity"),
        ["players.metric.donation_commitment"] = ("Komitmen Donasi", "Donation Commitment"),
        ["players.metric.debt_ratio"] = ("Rasio Utang", "Debt Ratio"),
        ["players.metric.risk_exposure"] = ("Eksposur Risiko", "Risk Exposure"),
        ["players.metric.risk_mitigation"] = ("Mitigasi Risiko", "Risk Mitigation"),
        ["players.metric.loan_repayment_discipline"] = ("Disiplin Pelunasan Pinjaman", "Loan Repayment Discipline"),
        ["players.metric.basic_need_profile"] = ("Profil Kebutuhan Dasar", "Basic Need Profile"),
        ["players.metric.collector_need_profile"] = ("Profil Kebutuhan Kolektor", "Collector Need Profile"),
        ["players.metric.specialist_need_profile"] = ("Profil Kebutuhan Spesialis", "Specialist Need Profile"),
        ["players.raw.economy"] = ("Ekonomi", "Economy"),
        ["players.raw.activity"] = ("Aktivitas", "Activity"),
        ["players.raw.commitment"] = ("Komitmen", "Commitment"),
        ["players.raw.starting_coins"] = ("Koin Awal", "Starting Coins"),
        ["players.raw.coins_held_current"] = ("Koin Saat Ini", "Coins Held (Current)"),
        ["players.raw.coins_saved"] = ("Koin Ditabung", "Coins Saved"),
        ["players.raw.coins_donated"] = ("Koin Donasi", "Coins Donated"),
        ["players.raw.coins_net_end"] = ("Koin Bersih Akhir Permainan", "Coins Net End Game"),
        ["players.raw.meal_order_income_total"] = ("Total Pendapatan Pesanan", "Meal Order Income Total"),
        ["players.raw.ingredients_collected"] = ("Bahan Terkumpul", "Ingredients Collected"),
        ["players.raw.ingredients_held_current"] = ("Bahan Tersimpan Saat Ini", "Ingredients Held (Current)"),
        ["players.raw.ingredients_wasted"] = ("Bahan Terbuang", "Ingredients Wasted"),
        ["players.raw.meal_orders_claimed"] = ("Pesanan Diklaim", "Meal Orders Claimed"),
        ["players.raw.meal_orders_passed"] = ("Pesanan Dilewati", "Meal Orders Passed"),
        ["players.raw.need_cards_purchased"] = ("Kartu Kebutuhan Dibeli", "Need Cards Purchased"),
        ["players.raw.needs_breakdown"] = ("Primer / Sekunder / Tersier", "Primary / Secondary / Tertiary Needs"),
        ["players.raw.gold_cards_held_end"] = ("Kartu Emas Tersisa", "Gold Cards Held End"),
        ["players.raw.actions_skipped"] = ("Aksi Dilewati", "Actions Skipped"),
        ["players.raw.loans_taken"] = ("Pinjaman Diambil", "Loans Taken"),
        ["players.raw.loans_repaid"] = ("Pinjaman Dibayar", "Loans Repaid"),
        ["players.raw.loans_unpaid_end"] = ("Pinjaman Belum Lunas", "Loans Unpaid End"),
        ["players.raw.collection_mission_complete"] = ("Misi Koleksi Selesai", "Collection Mission Complete"),

        ["rulesets.management"] = ("Manajemen Set Aturan", "Ruleset Management"),
        ["rulesets.title"] = ("Daftar Set Aturan Permainan", "Game Ruleset List"),
        ["rulesets.subtitle"] = ("Kelola aturan setup, alur aksi, dan scoring sesi.", "Manage setup rules, action flow, and session scoring."),
        ["rulesets.total_rulesets"] = ("Total Set Aturan", "Total rulesets"),
        ["rulesets.unified_subtitle"] = ("Buat Set Aturan baru, cek historinya, lalu aktifkan versi yang tepat sebelum sesi dimulai.", "Create new rulesets, review history, then activate the correct version before a session starts."),
        ["rulesets.tip.create"] = ("Buat: siapkan Set Aturan sesuai mode sesi.", "Create: build rulesets based on session mode."),
        ["rulesets.tip.versioning"] = ("Versi: aktifkan versi valid sebelum sesi.", "Versioning: activate a valid version before sessions."),
        ["rulesets.tip.safety"] = ("Keamanan: hapus Set Aturan yang sudah tidak dipakai.", "Safety: delete rulesets you no longer use."),
        ["rulesets.tip.versioning_draft"] = ("Versi: atur draft dulu, lalu aktifkan.", "Versioning: prepare draft first, then activate."),
        ["rulesets.tip.consistency"] = ("Konsistensi: isi form, JSON dibuat otomatis oleh sistem.", "Consistency: fill the form and let the system generate JSON automatically."),
        ["rulesets.tip.safety_before_start"] = ("Keamanan: ubah Set Aturan sebelum sesi dimulai.", "Safety: update rulesets before sessions start."),
        ["rulesets.create"] = ("Buat Set Aturan Baru", "Create New Ruleset"),
        ["rulesets.create_title"] = ("Buat Set Aturan baru", "Create new ruleset"),
        ["rulesets.create_subtitle"] = ("Isi form aturan permainan. JSON konfigurasi dibuat otomatis.", "Fill the gameplay rules form. Configuration JSON is generated automatically."),
        ["rulesets.edit"] = ("Edit aturan", "Edit rules"),
        ["rulesets.edit_title"] = ("Edit aturan Set Aturan", "Edit ruleset rules"),
        ["rulesets.edit_subtitle"] = ("Perbarui aturan untuk membuat versi baru tanpa mengubah riwayat versi lama.", "Update rules to create a new version without changing previous version history."),
        ["rulesets.quick_guide_title"] = ("Panduan cepat mengisi Set Aturan", "Quick guide to filling a ruleset"),
        ["rulesets.quick_guide_beginner"] = ("Mode PEMULA: rekomendasi kas awal 20, fitur pinjaman/asuransi/tabungan nonaktif.", "BEGINNER mode: recommended starting cash 20, with loan/insurance/saving features disabled."),
        ["rulesets.quick_guide_advanced"] = ("Mode MAHIR: rekomendasi kas awal 10, fitur pinjaman/asuransi/tabungan aktif.", "ADVANCED mode: recommended starting cash 10, with loan/insurance/saving features enabled."),
        ["rulesets.quick_guide_activation"] = ("Setelah menyimpan, aktifkan versi ruleset di sesi agar aturan ini benar-benar dipakai.", "After saving, activate the ruleset version in a session so these rules are actually applied."),
        ["rulesets.detail_title"] = ("Rincian Set Aturan", "Ruleset details"),
        ["rulesets.readonly_hint"] = ("Mode baca saja.", "Read-only mode."),
        ["rulesets.back_to_list"] = ("Kembali ke daftar", "Back to list"),
        ["rulesets.delete"] = ("Hapus", "Delete"),
        ["rulesets.save"] = ("Simpan Set Aturan", "Save Ruleset"),
        ["rulesets.update"] = ("Simpan Versi Baru", "Save New Version"),
        ["rulesets.analytics_link"] = ("Analitika Set Aturan", "Ruleset Analytics"),
        ["rulesets.total_versions"] = ("Total Versi", "Total Versions"),
        ["rulesets.active_versions"] = ("Versi Aktif", "Active Versions"),
        ["rulesets.status_label"] = ("Status Set Aturan", "Ruleset Status"),
        ["rulesets.status.archived"] = ("Diarsipkan", "Archived"),
        ["rulesets.status.available"] = ("Tersedia", "Available"),
        ["rulesets.config_summary"] = ("Ringkasan Konfigurasi Aturan", "Ruleset Configuration Summary"),
        ["rulesets.config_unavailable"] = ("Konfigurasi belum tersedia.", "Configuration is not available yet."),
        ["rulesets.version_history"] = ("Riwayat Versi Aturan", "Ruleset Version History"),
        ["rulesets.set_active"] = ("Jadikan Aktif", "Set as Active"),
        ["rulesets.form.core_setup"] = ("Aturan Dasar Sesi", "Session Core Rules"),
        ["rulesets.form.mode"] = ("Mode", "Mode"),
        ["rulesets.form.mode_beginner"] = ("PEMULA", "BEGINNER"),
        ["rulesets.form.mode_advanced"] = ("MAHIR", "ADVANCED"),
        ["rulesets.form.actions_per_turn"] = ("Jumlah Aksi per Giliran", "Actions per Turn"),
        ["rulesets.form.starting_cash"] = ("Kas Awal per Pemain", "Starting Cash per Player"),
        ["rulesets.form.player_ordering"] = ("Urutan Pemain", "Player Ordering"),
        ["rulesets.form.player_ordering_join_order"] = ("Urutan Bergabung (Sesi)", "Join Order (Session)"),
        ["rulesets.form.player_ordering_event_sequence"] = ("Aktivitas Pertama", "First Event"),
        ["rulesets.form.player_ordering_player_id"] = ("ID Pemain", "Player ID"),
        ["rulesets.form.player_ordering_username"] = ("Username (A-Z)", "Username (A-Z)"),
        ["rulesets.form.freelance_income"] = ("Pendapatan Kerja Lepas", "Freelance Income"),
        ["rulesets.form.weekday_features"] = ("Fitur Hari", "Weekday Features"),
        ["rulesets.form.friday_donation"] = ("Donasi Jumat", "Friday Donation"),
        ["rulesets.form.saturday_gold_trade"] = ("Perdagangan Emas Sabtu", "Saturday Gold Trade"),
        ["rulesets.form.sunday_rest"] = ("Minggu Libur", "Sunday Rest"),
        ["rulesets.form.constraints"] = ("Batasan", "Constraints"),
        ["rulesets.form.cash_min"] = ("Kas Minimum", "Cash Min"),
        ["rulesets.form.max_ingredient_total"] = ("Total Bahan Maksimum", "Max Ingredient Total"),
        ["rulesets.form.max_same_ingredient"] = ("Batas Bahan Sejenis", "Max Same Ingredient"),
        ["rulesets.form.primary_need_max_day"] = ("Batas Kebutuhan Primer / Hari", "Primary Need Max / Day"),
        ["rulesets.form.require_primary_first"] = ("Wajib Primer sebelum Lainnya", "Require Primary Before Others"),
        ["rulesets.form.economy_advanced"] = ("Ekonomi, Donasi, dan Fitur Mahir", "Economy, Donation, and Advanced Features"),
        ["rulesets.form.donation_min"] = ("Donasi Minimum", "Donation Min"),
        ["rulesets.form.donation_max"] = ("Donasi Maksimum", "Donation Max"),
        ["rulesets.form.gold_buy"] = ("Beli Emas", "Gold Buy"),
        ["rulesets.form.gold_sell"] = ("Jual Emas", "Gold Sell"),
        ["rulesets.form.loan_enabled"] = ("Pinjaman Aktif", "Loan Enabled"),
        ["rulesets.form.insurance_enabled"] = ("Asuransi Aktif", "Insurance Enabled"),
        ["rulesets.form.saving_goal_enabled"] = ("Target Tabungan Aktif", "Saving Goal Enabled"),
        ["rulesets.form.help.core_setup"] = ("Atur mode permainan, jumlah aksi, kas awal, urutan pemain, dan hasil kerja lepas.", "Set the game mode, actions per turn, starting cash, player ordering, and freelance reward."),
        ["rulesets.form.help.weekday_features"] = ("Tentukan apakah event khusus Jumat/Sabtu/Minggu berjalan di sesi ini.", "Decide whether Friday/Saturday/Sunday special events are enabled in this session."),
        ["rulesets.form.help.constraints"] = ("Batasan ini menjaga permainan tetap sesuai aturan stok bahan, kas, dan urutan kebutuhan.", "These constraints keep gameplay aligned with inventory, cash floor, and need-order rules."),
        ["rulesets.form.help.economy_advanced"] = ("Atur rentang donasi, izin transaksi emas, dan fitur khusus mode mahir.", "Set donation range, gold trade permissions, and advanced-mode features."),
        ["rulesets.config_read_guide"] = ("Gunakan ringkasan ini untuk cek apakah setup sesi, alur aksi harian, dan aturan ekonomi sudah sesuai yang Anda inginkan.", "Use this summary to verify that session setup, daily action flow, and economy rules match your intent."),
        ["rulesets.analytics.title"] = ("Analitika Set Aturan", "Ruleset Analytics"),
        ["rulesets.analytics.subtitle"] = ("Ringkasan Analitika per Set Aturan", "Analytics Summary per Ruleset"),
        ["rulesets.analytics.back"] = ("Kembali ke Analitika", "Back to Analytics"),
        ["rulesets.analytics.session_count"] = ("Jumlah sesi", "Session count"),
        ["rulesets.analytics.learning_aggregate"] = ("Agregat pembelajaran", "Learning aggregate"),
        ["rulesets.analytics.quest_aggregate"] = ("Agregat misi", "Quest aggregate"),
        ["rulesets.analytics.session"] = ("Sesi", "Session"),
        ["rulesets.analytics.events"] = ("Aktivitas", "Events"),
        ["rulesets.analytics.detail"] = ("Rincian", "Detail"),
        ["rulesets.analytics.empty_sessions"] = ("Belum ada sesi yang memakai Set Aturan ini.", "No sessions are using this ruleset yet."),
        ["rulesets.analytics.player_performance_empty"] = ("Belum ada performa pengguna yang bisa ditampilkan.", "No user performance available to display."),
        ["rulesets.analytics.user_learning"] = ("Performa Pembelajaran Pengguna", "User Learning Performance"),
        ["rulesets.analytics.user_quest"] = ("Performa Misi Pengguna", "User Quest Performance"),

        ["common.name"] = ("Nama", "Name"),
        ["common.description"] = ("Deskripsi", "Description"),
        ["common.status"] = ("Status", "Status"),
        ["common.created"] = ("Dibuat", "Created"),
        ["common.mode"] = ("Mode", "Mode"),
        ["common.action"] = ("Aksi", "Action"),
        ["common.detail"] = ("Rincian", "Detail"),
        ["common.view"] = ("Lihat", "View"),
        ["common.cancel"] = ("Batal", "Cancel"),
        ["common.version"] = ("Versi", "Version"),
        ["common.latest_version"] = ("Versi Terbaru", "Latest Version"),
        ["common.player"] = ("Pemain", "Player"),
        ["common.player_id"] = ("ID Pemain", "Player ID"),
        ["common.rank"] = ("Peringkat", "Rank"),
        ["common.turn_order"] = ("Urutan Giliran", "Turn Order"),
        ["common.session_id"] = ("ID Sesi", "Session ID"),
        ["common.ruleset_id"] = ("ID Set Aturan", "Ruleset ID"),
        ["common.ruleset"] = ("Set Aturan", "Ruleset"),
        ["common.transaction_amount"] = ("Nominal", "Amount"),
        ["common.time"] = ("Waktu", "Time"),
        ["common.direction"] = ("Arah", "Direction"),
        ["common.category"] = ("Kategori", "Category"),
        ["common.computed"] = ("Dihitung", "Computed"),
        ["common.start"] = ("Mulai", "Start"),
        ["common.finish"] = ("Selesai", "Finish"),
        ["common.session"] = ("Sesi", "Session"),
        ["common.na"] = ("Tidak Ada", "N/A"),
        ["status.session.created"] = ("Dibuat", "Created"),
        ["status.session.started"] = ("Dimulai", "Started"),
        ["status.session.ended"] = ("Selesai", "Ended"),
        ["status.session.cancelled"] = ("Dibatalkan", "Cancelled"),
        ["status.session.unknown"] = ("Tidak Diketahui", "Unknown"),
        ["status.ruleset.active"] = ("Aktif", "Active"),
        ["status.ruleset.draft"] = ("Draf", "Draft"),
        ["status.ruleset.archived"] = ("Diarsipkan", "Archived"),
        ["status.ruleset.retired"] = ("Pensiun", "Retired"),
        ["status.ruleset.unknown"] = ("Tidak Diketahui", "Unknown"),

        ["error.title"] = ("Terjadi Kesalahan", "An Error Occurred"),
        ["error.notice"] = ("Pemberitahuan Sistem", "System Notice"),
        ["error.message"] = ("Terjadi kesalahan saat memproses permintaan.", "An error occurred while processing your request."),
        ["error.submessage"] = ("Silakan coba lagi, atau cek rincian permintaan bila masalah berlanjut.", "Please try again, or check request details if the issue persists."),
        ["error.request_id"] = ("ID Permintaan", "Request ID"),
        ["error.dev_mode"] = ("Mode Pengembangan", "Development Mode"),
        ["error.dev_desc"] = ("Mode Pengembangan menampilkan rincian kesalahan untuk debugging lokal.", "Development mode shows detailed errors for local debugging."),
        ["error.dev_warning"] = ("Jangan aktifkan Pengembangan di produksi karena bisa mengekspos informasi sensitif.", "Do not enable Development in production because it can expose sensitive information."),
        ["error.dev_hint"] = ("Untuk debugging lokal, set ASPNETCORE_ENVIRONMENT ke Pengembangan.", "For local debugging, set ASPNETCORE_ENVIRONMENT to Development."),

        ["metric.total_event"] = ("Total Aktivitas Tercatat", "Total Recorded Activities"),
        ["metric.cash_in"] = ("Total Kas Masuk", "Total Cash In"),
        ["metric.cash_out"] = ("Total Kas Keluar", "Total Cash Out"),
        ["metric.net_cashflow"] = ("Arus Kas Bersih", "Net Cashflow"),
        ["metric.violations"] = ("Jumlah Pelanggaran Aturan", "Rule Violations"),
        ["metric.donation"] = ("Total Donasi", "Total Donations"),
        ["metric.gold_qty"] = ("Jumlah Emas", "Gold Qty"),
        ["metric.happiness"] = ("Total Poin Kebahagiaan", "Total Happiness Points"),
        ["metric.need_points"] = ("Poin Kebutuhan", "Need Points"),
        ["metric.need_bonus"] = ("Bonus Kebutuhan", "Need Bonus"),
        ["metric.donation_points"] = ("Poin Donasi", "Donation Points"),
        ["metric.gold_points"] = ("Poin Emas", "Gold Points"),
        ["metric.pension_points"] = ("Poin Pensiun", "Pension Points"),
        ["metric.saving_goal"] = ("Poin Target Tabungan", "Saving Goal Points"),
        ["metric.loan_unpaid"] = ("Pinjaman Belum Lunas", "Loan Unpaid"),
        ["metric.mission_penalty"] = ("Penalti Misi", "Mission Penalty"),
        ["metric.loan_penalty"] = ("Penalti Pinjaman", "Loan Penalty"),
        ["metric.orders_completed"] = ("Pesanan Selesai", "Orders Completed"),
        ["metric.inventory_ingredient"] = ("Stok Bahan", "Ingredient Inventory"),
        ["metric.actions_used"] = ("Aksi Terpakai", "Actions Used"),
        ["metric.primary_need_compliance"] = ("Kepatuhan Kebutuhan Primer", "Primary Need Compliance"),

        ["gameplay.title"] = ("Cuplikan permainan & turunan", "Gameplay snapshot & derived"),
        ["gameplay.raw"] = ("Variabel Permainan Mentah", "Raw Gameplay Variables"),
        ["gameplay.derived"] = ("Metrik Turunan", "Derived Metrics"),

        ["state.no_sessions"] = ("Belum ada sesi tersedia.", "No sessions available yet."),
        ["state.no_players"] = ("Belum ada data pemain.", "No player data yet."),
        ["state.no_player_data"] = ("Belum ada data pemain.", "No player data yet."),
        ["state.no_rulesets"] = ("Belum ada set aturan.", "No rulesets yet."),
        ["state.no_versions"] = ("Belum ada versi.", "No versions yet."),
        ["state.true"] = ("Ya", "Yes"),
        ["state.false"] = ("Tidak", "No")
    };

    public static string NormalizeLanguage(string? language)
    {
        return string.Equals(language, AuthConstants.LanguageEn, StringComparison.OrdinalIgnoreCase)
            ? AuthConstants.LanguageEn
            : AuthConstants.LanguageId;
    }

    public static string TranslateSessionStatus(HttpContext context, string? status)
    {
        var normalized = status?.Trim().ToUpperInvariant();
        return normalized switch
        {
            "CREATED" => Translate(context, "status.session.created"),
            "STARTED" => Translate(context, "status.session.started"),
            "ENDED" => Translate(context, "status.session.ended"),
            "CANCELLED" => Translate(context, "status.session.cancelled"),
            "CANCELED" => Translate(context, "status.session.cancelled"),
            _ => string.IsNullOrWhiteSpace(status) ? Translate(context, "status.session.unknown") : status!
        };
    }

    public static string TranslateRulesetStatus(HttpContext context, string? status)
    {
        var normalized = status?.Trim().ToUpperInvariant();
        return normalized switch
        {
            "ACTIVE" => Translate(context, "status.ruleset.active"),
            "DRAFT" => Translate(context, "status.ruleset.draft"),
            "ARCHIVED" => Translate(context, "status.ruleset.archived"),
            "RETIRED" => Translate(context, "status.ruleset.retired"),
            _ => string.IsNullOrWhiteSpace(status) ? Translate(context, "status.ruleset.unknown") : status!
        };
    }

    public static string Translate(HttpContext context, string key)
    {
        var lang = NormalizeLanguage(context.Session.GetString(AuthConstants.SessionLanguageKey));
        if (!Lexicon.TryGetValue(key, out var term))
        {
            return key;
        }

        return lang == AuthConstants.LanguageEn ? term.En : term.Id;
    }
}

public static class UiTextHttpContextExtensions
{
    public static string T(this HttpContext context, string key) => UiText.Translate(context, key);
    public static string TSessionStatus(this HttpContext context, string? status) => UiText.TranslateSessionStatus(context, status);
    public static string TRulesetStatus(this HttpContext context, string? status) => UiText.TranslateRulesetStatus(context, status);
}

