@Cashflowpoly.Api_HostAddress = http://localhost:5041

POST {{Cashflowpoly.Api_HostAddress}}/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "instructor",
  "password": "replace-with-your-password"
}

###
